### ISSUE TITLE
Handling SIGINT is broken

### ISSUE THREAD

**Issue by shusso** [gcarq/freqtrade#109]
Seems that in latest develop shutdown is b0rked
```
2017-11-16 10:21:05,446 - freqtrade - INFO - Checking buy signals to create a new trade with stake_amount: 0.010000 ...
^C2017-11-16 10:21:06,059 - freqtrade - INFO - Stopping trader and cleaning up modules...
^C2017-11-16 10:21:18,309 - freqtrade - INFO - Stopping trader and cleaning up modules...
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

only way to circumvent this is to `Ctrl-z` and kill the pid

**Comment by cih997** [comment]
This also happened to me but only when I tried to close while closing was in progress. So for example when I clicked twice (or more) Ctrl-c.

**Comment by gcarq** [comment]
locking/synchronizing `cleanup(...)` should fix this.
