### ISSUE TITLE
Filtering the whitelist With trend analysis

### ISSUE THREAD

**Issue by jblestang** [gcarq/freqtrade#110]
Pair trading implies that the pair is having the same trend, the various pairs should be filtrered before being added to the whitelist dynamically.

**Comment by vertti** [comment]
Pair trading is trading between BTC and some alt coin. There is no need for the different pairs to be in the same trend. Plus each pairs trend is free to change all the time so the initial "adding time trend" does not matter at all.

**Comment by jblestang** [comment]
Have a look there :

https://en.m.wikipedia.org/wiki/Pairs_trade

—
Jean-Baptiste

**Comment by jblestang** [comment]
I think we Are Naming « pair trading »  two things that are not the same?
