### ISSUE TITLE
Backtesting and validating a change in the trading algorithm

### ISSUE THREAD

**Issue by jblestang** [gcarq/freqtrade#134]
Currently the backtesting infrastructure allow you to test a modification of the trading algorithm. 

Backtesting data should be split in half, the first half to validate/tune your changes to the testing strategy and the second to validate it on an unknown test corpus. 

By doing so you can validate that your changes in the trading algorithm fits a general case and not only your test case.

**Comment by vertti** [comment]
You can already do this by creating the algorithm with the testdata, and then run the backtesting with `--live` data. So basically use live data for verification.

**Comment by jblestang** [comment]
OK Nice! You can close the issue
