### ISSUE TITLE
Rewriting some modules to make it testable

### ISSUE THREAD

**Issue by gcarq** [gcarq/freqtrade#14]
@vertti  @shusso I'm currently in the process to rewrite some modules to reduce complexity and remove unneeded wrapper classes. The main motivation was to make the code more testable. I've also included some unit tests. I will push it to `develop` branch this evening. Please look over it if it's fine for you and I would also like to create future PR against `develop` instead of `master`.

EDIT: I'll update this issue when it's pushed

**Comment by vertti** [comment]
Sounds good. Great that you are back to active development :) and thanks for the merges so far.

I have currently two branches under development. One is a completely new buy signal strategy that seems to be working relatively well with Parabolic SAR, ADX and EMA combination. All changes in that are limited to `analyze.py`.

The second PR is to enable the user to configure balance between using `ask` price and `last` when buying (the setting is a float in range 0..1 where setting for example `0.5` will use the price right between `last` price and `ask` price. Using `last` has the risk that you wont get buy, using ask basically guarantees you will pay overprice. This PR I'm sure I can port to your development branch and would actually love to have unit tests for it so your work comes in perfect time.

**Comment by gcarq** [comment]
Alright, I've touched everything except `analyze.py`, so there should be none or only a minor merge conflict :)

**Comment by gcarq** [comment]
Here we go: https://github.com/gcarq/freqtrade/commit/3473fd3c904503975f7343627ce693af4d2b8813. There is still an open issue on this branch regarding `/start` and `/stop` behaviour, just that you know.

**Comment by vertti** [comment]
Nice.

On a side note, should we use `pytest` instead of the default unittests? Pytest can run also normal python unittest but has cleaner asserts and plenty of other niceties.

And should we just drop the "support" for Poloniex? Poloniex market is only half of Bittrex anymore. We could remove the deadcode and reduce some of the complexity. I'm guessing we'll have our hands full without trying to support several exchanges.

**Comment by gcarq** [comment]
I have no strong feelings for the default unittests, but I've never tried `pytest` in the past, so I would be happy to accept PR's in this direction.

Yes I think we should drop the support for poloniex, but I would like to keep the exchange "API" as it is, because that makes it fast to integrate more exchanges

**Comment by vertti** [comment]
I think this issue is ready for closing.
