### ISSUE TITLE
That idiomatic Python

### ISSUE THREAD

**Issue by vertti** [gcarq/freqtrade#15]
Turns out the extra parentheses were needed, without them Python throws:

```
  File "/Users/vertti/dev/freqtrade/main.py", line 172, in handle_trade
    if 'stoploss' in CONFIG & current_profit < float(CONFIG['stoploss'])*100:
TypeError: unsupported operand type(s) for &: 'dict' and 'float'
```

Commit 69bfc2d777235688aea39902d65507d9d2d1a182 should be reverted.

**Comment by gcarq** [comment]
No the parentheses are not needed, the `&` is wrong at this place, because in python `&` is a binary operator. This should be `and`. It worked with the parentheses because it got evaluated as `bool` before. I'll fix this in a few hours

**Comment by vertti** [comment]
Thanks. My first project in Python so I'm sure there is more potholes I will still stumble in to.

**Comment by gcarq** [comment]
No problem, you get used to the syntax. Fixed with https://github.com/gcarq/freqtrade/commit/aea5331df8183deeb584d1f56e58cbe6ce7d849b
