### ISSUE TITLE
GDAX Support

### ISSUE THREAD

**Issue by szzhouke** [gcarq/freqtrade#152]
Is it possible to support GDAX?

**Comment by shusso** [comment]
We are looking into this as it looks really promising, which will have support for GDAX
https://github.com/Aurora-Team/BitcoinExchangeFH

but before we can do that, we need to fix few issues related on how the bot behaves with backtesting vs livedata using Bittrex. After that we have a clean base to start work on adding more support for other exhanges.

**Comment by czen88** [comment]
Have you looked at ccxt lib? https://github.com/ccxt/ccxt
This has support of many exchanges.

**Comment by shusso** [comment]
Closing per #230
