### ISSUE TITLE
Multiple Bittrex API keys 

### ISSUE THREAD

**Issue by cryptophunk** [gcarq/freqtrade#160]
It would be a great enhancement if we can add multiple bittrex API keys in the config to handle multiple accounts.

**Comment by chrisapril** [comment]
i think the easiest way to handle multiple keys is to have one separate bot for each account.

How long did it take until bittrex approved your additional accounts?

**Comment by vertti** [comment]
Like @chrisapril points out, just run multiple instances of the bot.
