### ISSUE TITLE
NO_API_RESPONSE 

### ISSUE THREAD

**Issue by ala273** [gcarq/freqtrade#161]
Hi I am getting the following error after running the bot for 20 mins. I can't seem to figure out the issue
`
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 63, in _process
    gen_pair_whitelist(_CONF['stake_currency']) if dynamic_whitelist else None
  File "/freqtrade/freqtrade/main.py", line 35, in refresh_whitelist
    health = exchange.get_wallet_health()
  File "/freqtrade/freqtrade/exchange/__init__.py", line 185, in get_wallet_health
    return _API.get_wallet_health()
  File "/freqtrade/freqtrade/exchange/bittrex.py", line 174, in get_wallet_health
    raise OperationalException('{message}'.format(message=data['message']))
freqtrade.OperationalException: NO_API_RESPONSE
```Issue `/start` if you think it is safe to restart.
2017-12-04 09:38:19,290 - freqtrade - ERROR - Got OperationalException. Stopping trader ...
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 63, in _process
    gen_pair_whitelist(_CONF['stake_currency']) if dynamic_whitelist else None
  File "/freqtrade/freqtrade/main.py", line 35, in refresh_whitelist
    health = exchange.get_wallet_health()
  File "/freqtrade/freqtrade/exchange/__init__.py", line 185, in get_wallet_health
    return _API.get_wallet_health()
  File "/freqtrade/freqtrade/exchange/bittrex.py", line 174, in get_wallet_health
    raise OperationalException('{message}'.format(message=data['message']))
freqtrade.OperationalException: NO_API_RESPONSE
2017-12-04 09:38:19,292 - freqtrade.rpc - INFO - *Status:* `stopped`
2017-12-04 09:38:19,496 - freqtrade - INFO - Changing state to: STOPPED
`

**Comment by jblestang** [comment]
This one should not be a fatal error I think.

**Comment by cryptophunk** [comment]
This error has been causing the bot to stop allot of times. I myself had to start the bot again like 6-8x a day

**Comment by ala273** [comment]
Yeah, it was getting really annoying so I made a bash script: run_prog.sh
and ran it in the background:
 
`
nohup bash run_prog.sh &

`
`
#!/bin/bash
# A simple script to ensure docker container keeps running stop

while true;
do
        now=$(date +"%T")
        echo "Automated script to keep docker running"
        echo "Current time: $now"
        docker start freqtrade
        sleep 900;
done
`                                                                                                                                        `

**Comment by cryptophunk** [comment]
Can this bash script be used for python?

**Comment by ala273** [comment]
https://stackoverflow.com/questions/13745648/running-bash-script-from-within-python

**Comment by cryptophunk** [comment]
Thanks @ala273

**Comment by chppppp** [comment]
Running this app from bash has some pitfalls, such as being unable to restart the process. I have been testing freqtrade in dry_run and I run into this error myself. 

Obviously freqtrade was built with some safety in mind, but if you want to remove this safety, comment out this last line in the _process() function in main.py

`    except OperationalException:
        rpc.send_msg('*Status:* Got OperationalException:\n```\n{traceback}```{hint}'.format(
            traceback=traceback.format_exc(),
            hint='Issue `/start` if you think it is safe to restart.'
        ))
        logger.exception('Got OperationalException. Stopping trader ...')
        #update_state(State.STOPPED) #comment out this line to prevent freqtrade from stopping on OperationalException`

I do not recommend this change as god forbid your trading gets bonked but for dry_run purposes I think it's OK.

**Comment by jblestang** [comment]
No Answer when getting a pair ticker or the wallet should be handled in my opinion without stopping the bot I think, it is really boring to have the bot stop 3/4 times a day. I’m going to look at how to handle this gracefully and will issue a PR

**Comment by pmaster555** [comment]
it would be excellent, I have these mistakes very often

**Comment by gcarq** [comment]
You're right, this should be handled without stopping the bot. I've created a PR to handle this exception as a temporary one, which will result a 30 second sleep and then continues normally.
