### ISSUE TITLE
Enhancement - read file for pair_whitelist

### ISSUE THREAD

**Issue by devalias** [gcarq/freqtrade#165]
Hi, instead of adding the btc pair in config.json can we just add the pair into a file, you can call it whitelist.txt.

**Comment by seansan** [comment]
is there a use case? json files are config files, only in a "certain" format

**Comment by gcarq** [comment]
I'm also curious if there is a use case. IMO implementing this would add to much complexity for offering not much value. The same can be achieved with a bash one-liner in a more transparent way

**Comment by shusso** [comment]
We might revisit this if there is a need, closing for now
