### ISSUE TITLE
Stoploss: not selling despite being reached

### ISSUE THREAD

**Issue by ctluciani** [gcarq/freqtrade#166]
I've noticed multiple occasions where trades dropped well below stoploss yet hung on to trades. I was using conservative values of -0.10 and -0.5, and had active trades with profits below -0.20. I've experienced this with sell_signal enabled and disabled.

**Comment by pan-long** [comment]
@ctluciani Can you paste your `config.json` here?

**Comment by glonlas** [comment]
I have the same issue, the bot does not sell at the stop-loss and neither at the max time.
I will share my conf.

**Comment by glonlas** [comment]
Here a config sample which has this issue

```json
{
    "max_open_trades": 15,
    "stake_currency": "BTC",
    "stake_amount": 0.001,
    "dry_run": false,
    "minimal_roi": {
        "160":  0.0,
        "30":  0.01,
        "20":  0.02,
        "0":  0.04
    },
    "stoploss": -0.1,
    "bid_strategy": {
        "ask_last_balance": 0.0
    },
    "exchange": {
        "name": "bittrex",
        "key": "",
        "secret": "",
        "pair_whitelist": [
            "BTC_ADA",
            "BTC_NEO",
            "BTC_NXT",
            "BTC_MCO",
            "BTC_XZC"
        ]
    },
    "experimental": {
        "use_sell_signal": true
    },
    "telegram": {
        "enabled": true,
        "token": "...",
        "chat_id": "..."
    },
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by ctluciani** [comment]
I don't have the config file I was using, lots of changes made to it since then, but I never once had stoploss trigger. I set the log level to Info where it would log when stoploss triggered, and stoploss functions when I run backtesting, so I'm not sure what's preventing it from working running normally. I'll see what I can find.

**Comment by glonlas** [comment]
I found the reason. In my case this is because I have enable the experimental feature for use_sell_signal.

If you have use_sell_signal = true it will ignore your stoploss

**Comment by jblestang** [comment]
Stop loss detection is done in min_roi_reached and the use_sell_signal is checked after : 

    # Check if minimal roi has been reached
    if not min_roi_reached(trade, current_rate, datetime.utcnow()):
        return False

    # Check if sell signal has been enabled and triggered
    if _CONF.get('experimental', {}).get('use_sell_signal'):
        logger.debug('Checking sell_signal ...')
        if not get_signal(trade.pair, SignalType.SELL):
            return False

**Comment by kryofly** [comment]
Aren't the correct logic: IF min_roi_reached() OR get_signal(SELL) THEN execute_sell()

Currently it reads: IF [min_roi_reached()] AND get_signal(SELL) THEN execute_sell()

(Assume both logics are under use_sell_signal = true policy).
