### ISSUE TITLE
Refactoring analyze

### ISSUE THREAD

**Issue by vertti** [gcarq/freqtrade#17]
@gcarq i'd like to get my new buy strategy into develop, but I think I'll start by writing bunch of tests for `analyze.py` and refactoring it a little. Is that ok or have you started on `analyze.py` already?

Drop me an email at janne dot sinivirta at gmail dot com and I'll invite you to our Slack, the Github issue tracker is probably not the best way to talk about ideas :)

**Comment by vertti** [comment]
I've started the refactoring of `analyze.py`.

**Comment by gcarq** [comment]
@vertti yeah sure it's ok for me, I didn't touched `analyze.py`.
Ok sounds good, I will drop you an email later today

**Comment by vertti** [comment]
Done in PR #18
