### ISSUE TITLE
Backtesting: wrong AVG profit

### ISSUE THREAD

**Issue by glonlas** [gcarq/freqtrade#177]
Hello,

I ran a backtesting with a `Using stake_amount: 0.001`, on the backtesting result of the, I saw that:

```
pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
BTC_XEM              1  2.49%         0.02490797 BTC            25
```

However, if the bot is doing only 1 trade at `0.001 BTC` and get a total profit of `0.02490797 BTC`. the result cannot be 2.49% (0.00249). Because 2.49% of 0.001 = 0.0010249 `0.001+(0.001*0.0249)`

Instead of 2.49% we have 249%.
The issue seems to come from here: https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L50

**Comment by gcarq** [comment]
@glonlas Good catch, thanks for reporting! That's pretty sure the root cause. If so, it also applies here https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L59

**Comment by glonlas** [comment]
@gcarq, I think the implementation of the backtesting is wrong. I found a bug here: https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L101

`Trade.amount`, is the number of cryptocurrency we are buying
`Trade.stake_amount`, is how many BTC we have invested.

`Trade.stake_amount` must be always equal to your config `config['stake_amount']`. But `Trade.amount` must change on every transaction. It is calculated by: `config['stake_amount'] / Open rate`

If my config['stake_amount'] = 0.001 BTC  (around $19), I should expect the backtesting to buy around 0.001 BTC of the cryptocurrency. But here, is always buying `0.001`of the crypto currency.

**Comment by glonlas** [comment]
Another explanation if the previous one was not clear.

If I setup my bot with a `stake_amount`at 0.001, I am expecting it to buy 0.001 BTC of cryptocurrency
If the open rate of the crypto is `0.00001175`, it must buy `85.1063829787` coins of the cryptocurrency (stake_amount / open_rate: 0.001/0.00001175 = 85.1063829787)

But the backtesting, it buying `0.001` coins of the cryptocurrency not `85.1063829787`

The bug is here: https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L101
The right implementation should be: 

`stake_amount=config['stake_amount'],`
`amount= config['stake_amount'] / row.open,`

**Comment by glonlas** [comment]
PR: https://github.com/gcarq/freqtrade/pull/201
