### ISSUE TITLE
Only sell coins in db, dont buy anymore.

### ISSUE THREAD

**Issue by chppppp** [gcarq/freqtrade#178]
Is there a setting to only *SELL* the coins being held and not perform anymore BUYS?

I have about 10 coins i want to ditch before building a new sqlite db. 

Thank you

**Comment by pmaster555** [comment]
delete db, sell the coin manually.

**Comment by aaur0** [comment]
You can issue a force sell command through the telegram bot.

**Comment by shusso** [comment]
Feel free to re-open if the above instructions weren't enough
