### ISSUE TITLE
Hyperopt not working

### ISSUE THREAD

**Issue by aaur0** [gcarq/freqtrade#180]
I did try to run hyperbot both as standalone and using mongodb. It doesn't spit out any meaning full results.

{
    "adx": 0,
    "fastd": 0,
    "green_candle": 1,
    "mfi": 1,
    "mfi-value": 20.0,
    "over_sar": 1,
    "rsi": 1,
    "rsi-value": 20.0,
    "trigger": 6,
    "uptrend_long_ema": 1,
    "uptrend_short_ema": 1,
    "uptrend_sma": 1
}
2017-12-13 18:34:47,631 - freqtrade.optimize.hyperopt - INFO - Best Result:
Made      0 buys. Average profit   nan%. Total profit was     nan. Average duration   nan mins.

It seems I am missing some configuration here.

**Comment by shusso** [comment]
@aaur0 thanks for the issue 👍  With what command did you run hyperopt? And also are you running from `master` or from `develop`?

By default in develop we don't show much if we don't win the "current best total_profit". E.g. for me running in latest develop I get
```
[freqtrade] > python3 freqtrade/main.py hyperopt -e 10
..........2017-12-14 09:12:04,758 - freqtrade.optimize.hyperopt - INFO - Best parameters:
{
    "adx": 1,
    "adx-value": 31.0,
    "fastd": 1,
    "fastd-value": 45.0,
    "green_candle": 0,
    "mfi": 0,
    "over_sar": 0,
    "rsi": 1,
    "rsi-value": 40.0,
    "trigger": 6,
    "uptrend_long_ema": 1,
    "uptrend_short_ema": 0,
    "uptrend_sma": 1
}
2017-12-14 09:12:04,759 - freqtrade.optimize.hyperopt - INFO - Best Result:
Made     15 buys. Average profit  0.77%. Total profit was   0.115. Average duration  38.0 mins.
```

**Comment by flightcom** [comment]
I also noticed that. I have a solution that I did not push yet. The problem is that if one try results in no trade, total_profit is `nan`, which comes first after sorting.

Returns this in your `optimizer`:
```
    return {
        'loss': trade_loss + profit_loss,
        'total_profit': total_profit,
        'status': STATUS_OK,
        'result': result
    }
```

and replace the sort function by:
```
    results = sorted(
        [r for r in trials.results if not np.isnan(r['total_profit'])],
        key=itemgetter('loss'))
```

**Comment by gcarq** [comment]
@flightcom Good catch!

**Comment by aaur0** [comment]
@shusso I ran it from develop. 
The command used: main.py hyperopt -e 5

@flightcom : Thanks. I'll try it out soon.

**Comment by aaur0** [comment]
@flightcom : np.isnan(r['total_profit']) is where the code is failing. It cannot find the key 'total_profit'. What am I missing here ?

**Comment by flightcom** [comment]
@aaur0 probably you didn't replace the `return` value of the optimizer function.
