### ISSUE TITLE
Profit command broken in develop

### ISSUE THREAD

**Issue by aaur0** [gcarq/freqtrade#190]
I pulled the latest code from develop and since then profit telegram command fails with error:

> 2017-12-16 03:13:31,241 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/freqtrade/freqtrade/rpc/telegram.py", line 106, in wrapper
    return command_handler(*args, **kwargs)
  File "/freqtrade/freqtrade/rpc/telegram.py", line 308, in _profit
    profit_closed_btc=round(sum(profit_btc_closed), 8),
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]

**Comment by shusso** [comment]
Tried to repro this with dry_run and forceselling 5 trades to get some data for profit, but was not able to.

**Comment by shusso** [comment]
@aaur0 could you please add some debugging e.g. 
`print(profit_btc_closed)`
around [here](https://github.com/gcarq/freqtrade/blob/e00f02b60396fed7ed89390db8363310ce262709/freqtrade/rpc/telegram.py#L297) ?

**Comment by gcarq** [comment]
I also cannot reproduce it. Both possible code path should work fine:
```
>>> from decimal import Decimal
>>> profit_btc_closed = []
>>> round(sum(profit_btc_closed), 8)
0

>>> from decimal import Decimal
>>> profit_btc_closed = [Decimal(0.000124), Decimal(1.00412), Decimal(2.4214)]
>>> round(sum(profit_btc_closed), 8)
Decimal('3.42564400')
```
How does your setup look like? And can you post the `open_rate` and `close_rate` from your database?
```
$ sqlite3 tradesv3.sqlite "SELECT open_rate, close_rate FROM trades;"
```

**Comment by aaur0** [comment]
I can't reproduce this either anymore. closing the issue.
