### ISSUE TITLE
MIN_TRADE_REQUIREMENT_NOT_MET

### ISSUE THREAD

**Issue by ravi94** [gcarq/freqtrade#204]
I m getting MIN_TRADE_REQUIREMENT_NOT_MET when trying to put ASK for $DGB . its well above the min requirement set by the bittrex. PFA screenshot .
Can someone help ?

![image](https://user-images.githubusercontent.com/3501525/34119139-16301a30-e447-11e7-8e12-897be349a2ef.png)

**Comment by glonlas** [comment]
Look like a nice UI, what is it?

**Comment by ravi94** [comment]
Its error while trying to "ask" on bittrex . 
Am i posting the issue on wrong channel ? apology i m new here

**Comment by glonlas** [comment]
@gcarq issue closed
