### ISSUE TITLE
Hyperopt with MongoDB broken

### ISSUE THREAD

**Issue by glonlas** [gcarq/freqtrade#206]
Since my [previous PR](https://github.com/gcarq/freqtrade/commit/512fcdbcb19f448dfeb46b7347a3053b46230f41#diff-4c21adf1de7a357821247a6e8d6abba3L37) was merged, I have introduced a regression on HyperOpt + MongoDB.

The code below shows how I have refactored the variable `PROCESSED`, because it needs now two parameters that are unknown at the global scope: "`pairs`" and "`ticker_interval`".
https://github.com/gcarq/freqtrade/commit/512fcdbcb19f448dfeb46b7347a3053b46230f41#diff-4c21adf1de7a357821247a6e8d6abba3L37

When we use MongoDB, the function `optimizer()` that use the global variable `PROCESSED` cannot have a copy of this variable updated from `starts()`. When we use MongoDB `PROCESSED` value is always `[]`.

I do not find any ways to pass to `optimizer()` the content of `PROCESSED` set in `start()`.
https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/hyperopt.py#L235-L236

This issue is only true when we use mongoDB.

Do you have any idea how can I solve this?

**Comment by gcarq** [comment]
Fixed with #218
