### ISSUE TITLE
Bittrex MIN_TRADE_REQUIREMENT_NOT_MET on 50k > satoshi order

### ISSUE THREAD

**Issue by khangee12** [gcarq/freqtrade#208]
HI!
i sell some XMG on bittrex but its show this error "MIN_TRADE_REQUIREMENT_NOT_MET " although my amount is also more than 50k satoshi. 

![image](https://user-images.githubusercontent.com/32769066/34178355-b7d9296c-e528-11e7-8986-d529b123c6b0.png)

![image](https://user-images.githubusercontent.com/32769066/34178377-c76fdf7e-e528-11e7-8f15-9ecf24aec5cd.png)

**Comment by glonlas** [comment]
Hello, is you issue related to this project?
