### ISSUE TITLE
Any way to have it trade using USD on Bitfinex? 

### ISSUE THREAD

**Issue by Nabk6** [gcarq/freqtrade#209]
Bitcoin has been dropping lately and it's bound for a much bigger drop soon. Anyway to do this using USD through something like Bitfinex?

**Comment by glonlas** [comment]
I did not try, but if you change your conf for `"stake_currency": "USD",` and only whitelisting coins that are trading is USD on Bittrex it should be good.

Dry test it first.

**Comment by shusso** [comment]
Closing per #230
