### ISSUE TITLE
New functionality (alert messages, /buy)

### ISSUE THREAD

**Issue by dertione** [gcarq/freqtrade#21]
Hi !

It's new Idea i would like to implement myself so i Share it here :
-create new thread which will check all money with the algo choosen and it send you alert when he think the money will grow up
-Create alert with slack of several money (update, bug fix etc..)
-Create command /buy /askBuy /askSell with the name of money and the amount in BTC for the parameters

(This functionality add the part of manual trader with lot of indications to make the good decision in addition to the bot)

For the bot :
Add a latency between the start of trader and the buy decision (10min for example) because i notice, it make Bad decision on the start of bot.

What do you think about it ?

**Comment by vertti** [comment]
For the latency: there is nothing different between decisions made when starting the bot to the decisions made at let's say 10 minutes. If you feel there is, then you have just had bad luck.

For slack signals etc: The bot looks for buy opportunities in the next few minutes, so if you want buy suggestions that you can do manually, you probably need different algorithm. There is already a lot of twitter bots etc that give you signals for buying longer term. I think our bot should not serve that need.

For the command to add a new currency, that sounds like useful feature that we should do. I suggest creating a separate issue for that and closing this. Feel free to create a pull request for that feature.

**Comment by dertione** [comment]
Ok so i am unlucky man lol.

Yes different algorithm but it Can be another solution of full robot trader. Maybe another program to do this.

I  notice that the bot buys at a higher price than it should be at this moment. It's juste feeling or true ?
I will create other issue / pull request for this suggestions to night.

Thank you :) !

**Comment by vertti** [comment]
It is currently buying with the ask price, which guarantees instant buy but is often more than we should bid with. I'm currently writing a configuration option to set your preferred price between ask and last price.

**Comment by dertione** [comment]
Ok thank you :) !
