### ISSUE TITLE
minimal system requirements?

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#210]
would 1 cpu 500mb ram on digital ocean be enough?

recently we saw 100cpu and had to hard reset

![image](https://user-images.githubusercontent.com/652395/34195464-f14d82e4-e55d-11e7-8386-eda02b207a67.png)

**Comment by glonlas** [comment]
This instance will be too small. I suggest min 1VPCU, 1GB of RAM.
Most important is the RAM.
About network, I did not check yet, but I think 1TB should be good.

**Comment by seansan** [comment]
​I think we should add this to readme. 1VPCU​ and 500mb ram was not enough.
There were huge CPU spikes that made the server unresponsive and needed
hard reset. Mem was used only half. When I moved to 2CPU and 2GB ram I was
fine.

**Comment by glonlas** [comment]
This is a good feedback, feel free to contribute to the README.

**Comment by pan-long** [comment]
Hmm, my bot on digitalocean looks fine (1VPCU, 512MB RAM with 1GB SWAP). I am using docker btw.

![image](https://user-images.githubusercontent.com/4057238/34252658-797cf3a8-e67f-11e7-8ffb-deb4b9f1264c.png)
