### ISSUE TITLE
Show USD price in telegram responses

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#212]
Buy request notification in telegram / possible improvements

(first: little new to python and this repo, but will ertainly contribute when I understand and know what I am doing). 

Would it be possible to add some improvements to messages in telegram?
- buy / sell / status : also show USD value of the trade? (giving us a sense of how much is being moved)
for example daily, profit column also show USD value
- for status table, profit colum show % if % (Or is this ratio?)
- for balance also add USD value?
- idem for status "what is our BTC wallet worth"

**Comment by gcarq** [comment]
I like the idea of showing the USD value. It would require some external source to fetch the price for `USD/<stake_currency>` and cache it for some amount of time, maybe coinmarketcap.com offers an API for that.

**Comment by glonlas** [comment]
I like this idea, PR in progress.  User will be able to select in which fiat they want to convert. We will cache the value (may be for 6 hours)

**Comment by glonlas** [comment]
You can check the PR #239, I have improved the bot to allow you to select the fiat you want to see in Telegram.

**Comment by shusso** [comment]
Fixed in #239
