### ISSUE TITLE
Buy command for telegram?

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#214]
Would it be an idea to add a buy command for the telegram bot? (and maybe sell)

But in essence, the bot buys when given the command, then follows the sell rules like setup

suppose the command would work like this

/buy DASH 1000 usd

meaning
- buy
- "stake_currency" + "_" + DASH = BTC_DASH
- for 1000 usd (usd can be made optional to add, meaning buy 1000 means buy for 1000 usd)

buy is possible, the buildup of the key pair also, only need to dive in, how to find the USD equivalant or similar for the BTC_DASH in this case that is buying bought, Option could be to take BTC_DASH/BTC_USD * BUY_VALUE or similar

Does this make sense?

Sample code for main.py (because order is manual needs lesser checks)

```
def create_trade_spec(currency string, stake_amount: float) -> bool:
    """
    Execute a buy for currency_buy pair and new trade record created
    :param currency: latter part of the currenycy to buy (will be appended later)
	:param stake_amount: amount of btc to spend
    :return: True if a trade object has been created and persisted, False otherwise
    """
    
    pair = currency + '_' + _CONF['stake_currency']

	logger.info(
        'Trying to create a new trade for %s with stake_amount: %f ...',
        pair, stake_amount
    )

	whitelist = copy.deepcopy(_CONF['exchange']['pair_whitelist'])
    # Check if stake_amount is fulfilled
    if exchange.get_balance(_CONF['stake_currency']) < stake_amount:
        raise DependencyException(
            'stake amount is not fulfilled (currency={})'.format(_CONF['stake_currency'])
        )

    # Calculate amount
    buy_limit = get_target_bid(exchange.get_ticker(pair))
    amount = stake_amount / buy_limit

    order_id = exchange.buy(pair, buy_limit, amount)

	# Create trade entity and return
    rpc.send_msg('*{}:* Buying [{}]({}) with limit `{:.8f}`'.format(
        exchange.get_name().upper(),
        pair.replace('_', '/'),
        exchange.get_pair_detail_url(pair),
        buy_limit
    ))

	# Fee is applied twice because we make a LIMIT_BUY and LIMIT_SELL
    trade = Trade(
        pair=pair,
        stake_amount=stake_amount,
        amount=amount,
        fee=exchange.get_fee() * 2,
        open_rate=buy_limit,
        open_date=datetime.utcnow(),
        exchange=exchange.get_name().upper(),
        open_order_id=order_id
    )
    
	Trade.session.add(trade)
    Trade.session.flush()
    
	return True
```

Sample code for telegram (because order is manual needs lesser checks)

```
@authorized_only
def _buy(bot: Bot, update: Update) -> None:
    """
    Handler for /buy <id>.
    Buys the given trade at current price for value
    :param bot: telegram bot
    :param update: message update
    :return: None
    """
    if get_state() != State.RUNNING:
        send_msg('`trader is not running`', bot=bot)
        return

    currency = update.message.text.replace('/buy', '').strip()
    # Get currency bit from command line
	if currency == '':
        # Error here
        return
    # Get USD value from commandline; maybe add switch for when USD supplied then buy USD value otherwise BTC value
	if value == '':
        # Error here
        return

    # Query for trade
    trade = Trade.query.filter(and_(
        Trade.id == currency,
        Trade.is_open.is_(True)
    )).first()
    if not trade:
        send_msg('Invalid argument. See `/help` to view usage')
        logger.warning('/buy: Invalid argument received')
        return

    _exec_forcebuy(trade)

def _exec_forcesell(trade: Trade) -> None:
    # Get current rate and execute sell
    current_rate = exchange.get_ticker(trade.pair)['bid']
    from freqtrade.main import execute_buy
    execute_buy(trade, current_rate)

```

**Comment by shusso** [comment]
Hi @seansan thanks for the issue and code-snippets.

> Would it be an idea to add a buy command for the telegram bot? (and maybe sell)

The only worry I have is that how should the bot behave after those buys have been made. Currently (as from #22) the bot will only sell to the amount purchased, so lets say you manually buy BTC_DASH for 1000$ and then after 5s the bot sees an opportunity to sell it, should it sell it?

#22 also applies to sell as well, meaning the bot isn't selling anything it hasn't purchased.

**Comment by seansan** [comment]
​>> BTC_DASH for 1000$ and then after 5s the bot sees an opportunity to
sell it, should it sell it?

in short yes

Suppose we receive human signal, say google, say CNBC ... we expected a
certain rise

then we can manuallu override stake and trade pair by making a manual buy

(and yes very welcome: let the bot monitor it for me afterwards)

**Comment by shusso** [comment]
@seansan  Why would you want to do this using the bot instead of Bittrex webpage?

**Comment by seansan** [comment]
​cause using telegram is super handy​

**Comment by shusso** [comment]
That it is, but I'm thinking that it might be outside of the scope of this project as we currently want the Bot to be as independent as possible. We do have `forcesell` as the last option if everything goes wrong

**Comment by seansan** [comment]
​"independent as possible" : that it still is, it can sell according to
rules

dont worry we are not taking away its indepence ;) I mean the not still
does what it does

only addition is we can start a buy

seems to me like a quick win, forcesell, then also have forcebuy
​

**Comment by shusso** [comment]
We might revisit this later, but currently there isn't a plan for implementing this. PRs are welcome.
