### ISSUE TITLE
Sell amount equal to amount purchased

### ISSUE THREAD

**Issue by alangvand** [gcarq/freqtrade#22]
At the moment, the bot sells whatever the balance is for the given pair on the exchange. It would be nice to have an option to sell only the amount of coin previously purchased by the bot. This way, freqtrade won't accidentally mess with whatever trades I am doing manually on the side.

**Comment by vertti** [comment]
Agreed, this needs to be fixed.

**Comment by gcarq** [comment]
Fixed with 0.14.0
