### ISSUE TITLE
Stability Improvements

### ISSUE THREAD

**Issue by shusso** [gcarq/freqtrade#226]
Things needing to be fixed

- [x] strategy (buy, sell) improvements
- [x] improve test coverage (moar unittests)
- [x] Bittrex stability improvements
- [x] Backtesting profit calculations (#200)
- [x] Telegram stability improvements

**Comment by glonlas** [comment]
1. Do we still have Telegram instability? 
1. "improve test coverage (moar unittests)" What % we target?

**Comment by fashaikh** [comment]
telegram bot has been working fine for me .. for the past 24 hrs. what instability shodul we be looking out for ?

**Comment by shusso** [comment]
seems that things got better. Good job everybody 👍
