### ISSUE TITLE
Whitelist pair after sale

### ISSUE THREAD

**Issue by alangvand** [gcarq/freqtrade#23]
Currently, the purchased pair is still removed from the whitelist even after it's sold. In my mind it would make sense if it is whitelisted again once sold. Would make a pull request on this, but my limited python skills keep me from seeing how to ideally get the whitelist object into execute_sell.

**Comment by StarBruck** [comment]
`def execute_sell(trade: Trade, current_rate: float) -> None:
	"""
	Executes a sell for the given trade and current rate
	:param trade: Trade instance
	:param current_rate: current rate
	:return: None
	"""
	# Get available balance
	currency = trade.pair.split('_')[1]
	balance = exchange.get_balance(currency)

	profit = trade.exec_sell_order(current_rate, balance)
	whitelist.append(trade.pair)
	message = '*{}:* Selling [{}]({}) at rate `{:.8f} (profit: {}%)`'.format(
		trade.exchange.name,
		trade.pair.replace('_', '/'),
		exchange.get_pair_detail_url(trade.pair),
		trade.close_rate,
		round(profit, 2)
	)
	logger.info(message)
	telegram.send_msg(message)`

Note that I use tabs instead of spaces. Replace execute_sell with this function, that should whitelist it again once sold.

**Comment by vertti** [comment]
Yep, another clear bug. Isn't it nice to have a good incentive to learn Python? :)

**Comment by alangvand** [comment]
You are absolutely right, and it's part of the reason why I looked into this project in the first place. Small, simple and might earn me some money along the way :) I'll see if I'm able to fix it.

**Comment by alangvand** [comment]
Made a pull request. Change should be made to telegram forcesell also, or ideally forcesell should use execute_sell()

**Comment by EricLim110** [comment]
Did a dry run of freqtrade today, I force sold a purchased pair today during a loss and it seems like it is still removed from the white list.

2017-10-04 15:39:58,167 - __main__ - DEBUG - Ignoring BTC_ARK in pair whitelist

Could my issue be the same as this one? Apologies as I am still very new to Python.

**Comment by alangvand** [comment]
Force sell from the Telegram bot does unfortunately use a separate function to sell which currently keeps the pair removed from the whitelist. Should be fixed.

**Comment by EricLim110** [comment]
I'll try to look into it as well despite my shallow knowledge of Python, it is always interesting to learn though.

**Comment by gcarq** [comment]
@EricLim110 which branch are you using? This should be fixed with https://github.com/gcarq/freqtrade/commit/d73c656514c993fc018361e21cd4b47a4c0bc39d on develop

**Comment by EricLim110** [comment]
@gcarq Turns out I was using the files on master all along. Apologies. I am still very new to everything here so I am still a little lost.

I will try out the develop versions soon and thanks for you help!

**Comment by gcarq** [comment]
No problem! This project is still in a very early state so until things settle down a bit you are better of using the `develop` branch

**Comment by EricLim110** [comment]
Just got the latest commit from the develop branch, everything works like a charm now!
