### ISSUE TITLE
Pump Detection [feature request]

### ISSUE THREAD

**Issue by tkso1997** [gcarq/freqtrade#233]
Hey guys!
I really like the bot! Would it be possible to implement some basic pump detection method based on increasing buy volumes during a defined period (like x% gain during the last x minutes), to buy very quickly and sell immediately afterwards?

**Comment by jblestang** [comment]
You could change the buy/sell trigger to be based on sell volule and change the time interval to 1 minute, maybe that would be enought

**Comment by tkso1997** [comment]
unfortunately my python skills are not the best, could you give me some hints where I can find the particular settings (in which file) ...

**Comment by jblestang** [comment]
Have a look in analysis.py you have two functions (populated_sell_signal, populate_sell_trend) and one other called populate_indicators. 

You need to fill the criteria for pump detection in buy_signal and criteria for end of pump detection in sell_signal.

**Comment by glonlas** [comment]
If you have the detection logic, we can add it into the documentation in a new section: `Shared strategies`, until we have the feature to use external file for strategies.

**Comment by glonlas** [comment]
You have CCI indicator in `develop` branch, you can use it to detect pump.
Feel free to close this issue.

**Comment by pmaster555** [comment]
where is new section: Shared strategies ?

**Comment by glonlas** [comment]
It does not exist yet. However, meet us on Slack, there is a lot discussion about strategies.

**Comment by shusso** [comment]
Join slack to discuss if haven't already [here](https://join.slack.com/t/highfrequencybot/shared_invite/enQtMjQ5NTM0OTYzMzY3LWMxYzE3M2MxNDdjMGM3ZTYwNzFjMGIwZGRjNTc3ZGU3MGE3NzdmZGMwNmU3NDM5ZTNmM2Y3NjRiNzk4NmM4OGE)

**Comment by mvclaudianobj** [comment]
what new link for slack ?

**Comment by hroff-1902** [comment]
See at the bottom of the initial docs page: https://www.freqtrade.io/en/latest/#help-slack

**Comment by mvclaudianobj** [comment]
tks
