### ISSUE TITLE
Is "use_sell_signal": false still experimental?

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#234]
"experimental": {
        "use_sell_signal": false
    },

**Comment by glonlas** [comment]
Yes, this is still considered experimental. The indicators used by this function are (IMHO) not ready. My bot lost a lot of great opportunities with this option and it forced the bot to sell some trades with a loss.

Once it will be upgraded and not considered experimental this feature will be integrated into the bot.

**Comment by kryofly** [comment]
What exactly are considered experimentally?
A sell is symmetrical to buy. Consider RSI > 30 and RSI < 70.
