### ISSUE TITLE
Retry on "Got invalid response" during backtesting

### ISSUE THREAD

**Issue by macd2** [gcarq/freqtrade#238]
Backtesting:
Example: `requests.exceptions.ContentDecodingError: Got invalid response from bittrex params=(BTC_NAUT)` this is error should be skipped and the coin marked as "N/A" on the results.

Else every "Got invalid response" breaks the backtest routine and there are many coins not working.

Ideal would be a mark in the database so the bot check every x hours if the coin is now available if so send a notification via telegram if not keep ignoring.

**Comment by gcarq** [comment]
Thanks for reporting that, this exception is not bound to a specific coin, but affects their whole API.
Right now this exception isn't handled within backtesting/hyperopt. A simple retry mechanism should be enough, as it only affects the download part.


> Ideal would be a mark in the database so the bot check every x hours if the coin is now available if so send a notification via telegram if not keep ignoring.

As mentioned above this is an issue with their whole API and not bound to a specific coin.

**Comment by shusso** [comment]
please re-open if still persists 👍
