### ISSUE TITLE
ERROR API Key invalid

### ISSUE THREAD

**Issue by tkso1997** [gcarq/freqtrade#240]
I get the following after some time and the bot stopps ... is there by any chance a way of automatically restarting it, to save your coins ...

Thanks 

```
Status: Got OperationalException:
Traceback (most recent call last):
  File "./freqtrade/main.py", line 89, in _process
    trade.update(exchange.get_order(trade.open_order_id))
  File "/home/thorsten/freqtrade/freqtrade-new/freqtrade/freqtrade/exchange/__init__
line 163, in get_order
    return _API.get_order(order_id)
  File "/home/thorsten/freqtrade/freqtrade-new/freqtrade/freqtrade/exchange/bittrex.py", line 152, in get_order
    order_id=order_id))
freqtrade.OperationalException: APIKEY_INVALID params=(6e64a887-a402-445c-94d7-5bc73c2d08b5)
Issue /start if you think it is safe to restart.
```

**Comment by glonlas** [comment]
I have the same experience as well. My guess is on the optimization made few days ago. And we get throttled. 

We should improve the bot to handle it properly.

**Comment by gcarq** [comment]
It happens every now and then. My assumption is that there is an internal timeout at bittrex side.

A possible solution would be to handle this exception gracefully the first time and only require intervention if it happens a second or third time in a row. That way we can be sure it isn't a configuration issue or that the account has been disabled.

**Comment by tkso1997** [comment]
Any suggestion for a way of restarting it automatically till there is a proper fix / solution for the problem?

**Comment by seansan** [comment]
I have seen this also now 2 days in a row. Maybe the bot should not stop immediately and we should allow a "grace" value to be set in config. Only if we have this error 3 times in a row then exit bot. I dont think breaking on 1st occurence is the best solution: because this has now happened several times (and our API keys are fine)

**Comment by Aiden-aiden** [comment]
Any solution to this problem ?

**Comment by Aiden-aiden** [comment]
Hey ?

**Comment by seansan** [comment]
Idea to: 
- make it a warning?
- validate on startup, and if OK after ignore?
- try to revalidate 3 times, if 4th still error then exit, else continue

![image](https://user-images.githubusercontent.com/652395/35612426-0997e6ce-0669-11e8-9d73-264057c476b3.png)

**Comment by seansan** [comment]
What about a relative simple fix, something long the lines of:

around here https://github.com/gcarq/freqtrade/blob/develop/freqtrade/exchange/bittrex.py#L152

```
        if not data['success']:
            if 'APIKEY_INVALID' in str(data['message']):
                // option 1 : do nothing and continue
                // option 2 : a. create a global list with counter + timestamp;
                // option 2 : b. on exception access global list, if last exception within 5 minutes then update counter+1 & update timestamp; else reset counter to 0
                // option 2 : c. check if counter > 2, then rais exception and exit
                // option 3 : some other cool solution
			else:
                Bittrex._validate_response(data)
                raise OperationalException('{message} params=({pair})'.format(
                    message=data['message'],
                    pair=pair))
```

Let us know your thoughts.. the sooner this is fixed .. the merrier ;)

**Comment by thorK65** [comment]
I like option 2!!

**Comment by ElanHasson** [comment]
Same.

**Comment by ChrisRut** [comment]
Additionally shouldn't there be some sort of exponential backoff: https://bitcoin.stackexchange.com/questions/53778/bittrex-api-rate-limit

**Comment by seansan** [comment]
So we should at least not go faster than 1 req per second

**Comment by seansan** [comment]
btw: this happens to my bot now every day since 1 month ... I restart it every morning when I wake up ...

**Comment by shusso** [comment]
please re-open if issue still persists 👍
