### ISSUE TITLE
Blacklisting a coin

### ISSUE THREAD

**Issue by tkso1997** [gcarq/freqtrade#252]
Looking for a way to blacklist coins when using —dynamic-whitelist.
Is there already something implemented?

**Comment by pmaster555** [comment]
not yet

**Comment by kryofly** [comment]
I think there is two implementation floating around in the forks.

**Comment by jblestang** [comment]
There is one available (not tested yet) here : https://github.com/gcarq/freqtrade/compare/develop...jblestang:pair_blacklist

**Comment by tkso1997** [comment]
thanks!!!

**Comment by jblestang** [comment]
Have you tried it?

**Comment by glonlas** [comment]
Let’s try it, add tests and create a pull request :)

**Comment by jblestang** [comment]
I need to test two new functions (no test exists yet for them) and i’m Not comfortable with the way unit tests are design/written do you mind helping me on slack?

**Comment by glonlas** [comment]
Of course not, I will be glad to help you on Slack.
