### ISSUE TITLE
Visualize live backtesting

### ISSUE THREAD

**Issue by Ramses2056** [gcarq/freqtrade#261]
Hi there, I really enjoy building strategies for the bot, but I didn't figure out how to plot the graphs so I can see the live performance of the bot. can someone help me out?

**Comment by gcarq** [comment]
There is a plotting script in `scripts/plot_dataframe.py`, which uses your defined strategy and plots it with matplotlib for the given pair (See line 53). It should be self explanatory (at least I hope it is).

**Comment by Ramses2056** [comment]
Thank you!!
