### ISSUE TITLE
The status  command is slow

### ISSUE THREAD

**Issue by jblestang** [gcarq/freqtrade#278]
With many trades in progress, the /Status command is slow, this is due to the fact that it fetches the latest value from the exchange, we should cache this value has it it being already fetched in _process

**Comment by shusso** [comment]
I also noticed this when I was testing the latest changes.

**Comment by jblestang** [comment]
I’ve a fix for this and will submit it for discussion

**Comment by seansan** [comment]
+1

**Comment by glonlas** [comment]
This is now fixed in `develop` branch. Thanks @jblestang for the PR.
