### ISSUE TITLE
config.jason max open trades = 0 Error 

### ISSUE THREAD

**Issue by macd2** [gcarq/freqtrade#282]
when set ```"max_open_trades": 0,``` bot gives an error. 

Setting would be useful to switch strates an let the bot just close all open positions according to "old" strat.

**Comment by shusso** [comment]
thanks for the issue @macd2 👍 

> when set "max_open_trades": 0, bot gives an error  

The minimum `max_open_trades` is currently set to `1` per the [jsonschema](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/misc.py#L208) validation. This behaviour is to be expected, as from the bots perspective the config isn't valid.

> Setting would be useful to switch strates an let the bot just close all open positions according to "old" strat.

IIRC if you put the `pair_whitelist` empty in your config, the bot shouldn't make any buy trades.

**Comment by shusso** [comment]
Feel free to re-open if the problem persists
