### ISSUE TITLE
Get error on pip install  

### ISSUE THREAD

**Issue by birdmoney11** [gcarq/freqtrade#285]
While setting up and on the "$ pip install -r requirements.txt" step I keep running into this issue.

```
Collecting` tabulate==0.8.2 (from -r requirements.txt (line 21))
  Using cached tabulate-0.8.2.tar.gz
Collecting pymarketcap==3.3.141 (from -r requirements.txt (line 22))
  Using cached pymarketcap-3.3.141.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-D0hM4B/pymarketcap/setup.py", line 12, in <module>
        with open(os.path.join(BASEDIR, "README.md"), encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-D0hM4B/pymarketcap/
```

I've tried everything from updating python and pip and still no avail. 
*using Linux mint

Thanks in advance.

**Comment by shusso** [comment]
thanks for the issue @birdmoney11 I'm suspecting your pip is pointing to python2. So make sure you have python3.6 and pip is pointing to the python3.6 installation.

**Comment by shusso** [comment]
You can always type `pip3.6` instead of `pip` to make sure it installs to correctly

**Comment by shusso** [comment]
Feel free to re-open if above didn't fix your issue 👍

**Comment by birdmoney11** [comment]
Dear shusso, 
Okay so Ive managed to upgrade pip and try again, but this time I get another error. 

` running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/talib
    copying talib/test_abstract.py -> build/lib.linux-x86_64-3.6/talib
    copying talib/test_data.py -> build/lib.linux-x86_64-3.6/talib
    copying talib/test_func.py -> build/lib.linux-x86_64-3.6/talib
    copying talib/__init__.py -> build/lib.linux-x86_64-3.6/talib
    copying talib/deprecated.py -> build/lib.linux-x86_64-3.6/talib
    copying talib/test_stream.py -> build/lib.linux-x86_64-3.6/talib
    running build_ext
    building 'talib.common' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/talib
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/usr/include/python3.6m -c talib/common.c -o build/temp.linux-x86_64-3.6/talib/common.o
    talib/common.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i66wjn49/TA-Lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-99w42fv_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-i66wjn49/TA-Lib/`

At first I thought it was a problem with the TA-Lib so i went and reinstalled it, but I still get the same problem.

Thanks in advanced.

**Comment by underscrew** [comment]
I am getting the same error. Tried on two different systems, ubuntu and xubuntu. Got the same error following all the instructions.

**Comment by shusso** [comment]
@birdmoney11 @underscrew 

Can you give me the output of the following commands
```
python --version
python3 --version
pip --version
pip3 --version
```

Also it might be that you need to have the python-dev package installed
```
sudo apt-get install python3-dev
```

**Comment by underscrew** [comment]
@shusso I ran `sudo apt-get install python3-dev` and still got the same error.

python --version
Python 2.7.12

python3 --version
Python 3.5.2

pip --version
pip 9.0.1 from /home/vuser/.local/lib/python2.7/site-packages (python 2.7)

pip3 --version
pip 9.0.1 from /usr/local/lib/python3.6/dist-packages (python 3.6)

**Comment by shusso** [comment]
Where is your python3.6 installed to? It seems that your python3 is pointing to python3.5.2 and pip3 points to python3.6

**Comment by underscrew** [comment]
@shusso 
```
which python3.6
/usr/bin/python3.6
```
```
python3.6 -V
Python 3.6.3
```
I don't get why are you asking about the python3 and pip3, if am supposed to run pip3.6 and python3.6.

**Comment by birdmoney11** [comment]
@shusso 

Here is what I get when I run the commands.

```
sudo apt-get install python3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dev is already the newest version (3.5.1-3).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
speedy@speedy ~ $ python --version
Python 2.7.12
speedy@speedy ~ $ python3 --version
Python 3.6.3
speedy@speedy ~ $ pip --version
pip 9.0.1 from /usr/local/lib/python3.6/dist-packages (python 3.6)
speedy@speedy ~ $ pip3 --version
pip 9.0.1 from /usr/local/lib/python3.6/dist-packages (python 3.6)
```

**Comment by shusso** [comment]
@birdmoney11 I think you need to install the python3.6-dev package as I think python3-dev is pointing to python3.5.2
https://packages.ubuntu.com/search?keywords=python3.6-dev

**Comment by Trips2007Rgg** [comment]
My solution for python3.6 was:

apt-get install python3.6-dev
