### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by tkso1997** [gcarq/freqtrade#288]
I am using a script on Tradingview that gives nice buy/sell signals (wt1 crossing wt2). Its written using Tradingviews pine. How could I implement It in the bot?

```
n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
 
ap = hlc3 
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)
 
wt1 = tci
wt2 = sma(wt1,4)
```

**Comment by shusso** [comment]
Thanks for the issue 👍 I think you have to translate that Tradingview pine into Python functionality with `pandas` and `ta-lib`. I personally have no experience in Tradingview so cannot help you there.  

For reference the current buy algo can be found [here](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/analyze.py#L73-L92). We already have quite alot of popular indicators [here](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/analyze.py#L40-L70).
