### ISSUE TITLE
Separate custom buy and sell values into a separate file

### ISSUE THREAD

**Issue by devalias** [gcarq/freqtrade#290]
It would be nice if the buy and sell settings in analyze.py were moved into a separate file like config.json, that way on a git pull the custom settings added won't get overwritten.

**Comment by shusso** [comment]
Or we could offer a default algo which could be then overwritten by personal one. That's a really good idea @devalias  👍

**Comment by glonlas** [comment]
:+1: 
This is a feature we have already discussed and it is on our roadmap. As said @shusso it will be a default algo provided by the bot that will be overwritten by personal file.

**Comment by ElanHasson** [comment]
Please take a look at my comments in #308 for consideration for this feature.

**Comment by crypdick** [comment]
@glonlas is the roadmap public?

**Comment by crypdick** [comment]
@ElanHasson I like the idea of a plug-in host. I think it would be easy to implement #384 if the plug-in host had a method to summarize the signals of its child plug-ins.

**Comment by shusso** [comment]
This is supported in develop. Please see the [docs](https://github.com/gcarq/freqtrade/blob/develop/docs/bot-optimization.md)
