### ISSUE TITLE
Support Manual Trades

### ISSUE THREAD

**Issue by ElanHasson** [gcarq/freqtrade#298]
It would be great if you could trigger a buy order to be managed by the bot for selling, skipping the buy signal.

**Comment by glonlas** [comment]
Hello,

This question was already discussed. The bot doesn’t target to become an exchange front-end.
 
Thanks

**Comment by ElanHasson** [comment]
That is understandable.

I think there is a benefit to being able to take advantage of the sell signals.

If I made a PR would it be considered?
