### ISSUE TITLE
hyperopt calculate_loss objective function explanation

### ISSUE THREAD

**Issue by zjong** [gcarq/freqtrade#303]
I'm trying to understand the calculate_loss function in hyperopt.py, especially the formula to derive trade_loss. Can @gcarq or someone please give me an insight or point me to a reference?

**Comment by shusso** [comment]
@zjong I think @vertti is the man you are looking for 👍

**Comment by shusso** [comment]
Please see the docs https://github.com/gcarq/freqtrade/blob/develop/docs/hyperopt.md
if that doesn't help, please join our slack channel [here](https://join.slack.com/t/highfrequencybot/shared_invite/enQtMjQ5NTM0OTYzMzY3LWMxYzE3M2MxNDdjMGM3ZTYwNzFjMGIwZGRjNTc3ZGU3MGE3NzdmZGMwNmU3NDM5ZTNmM2Y3NjRiNzk4NmM4OGE)
