### ISSUE TITLE
Implement strategies as a plugin based system

### ISSUE THREAD

**Issue by ElanHasson** [gcarq/freqtrade#308]
Strategies should be implemented as a plugin system to enable a host of benefits, such as:

- Surviving container rebuilds, just like sqlite and config
- Be self contained to facilitate sharing and/or independent versioning

I think plugins should:
- be responsible for populating their own indicators
- have the ability to support their own configuration via their own block of json in the config (to prevent key leakage to possibly malicious code)
- support either buy or sell
- have access to a 'plugin host' which would allow Plugin A to be created which can consume Plugin B, C, etc to be able to 'chain' them together to produce more sophisticated logic

**Comment by glonlas** [comment]
I suggest you to contribute to this issue that already talk about this subject.

https://github.com/gcarq/freqtrade/issues/290

**Comment by jblestang** [comment]
What about specifying a strategy name in the config and the bot would import a `get_XXX_buy_signal` And a `get_XXX_sell_signal` Method from module freqtrade.strategy.XXX 

Setting a list of strategies would call each function by their list order in the config file.

[https://stackoverflow.com/questions/8790003/dynamically-import-a-method-in-a-file-from-a-string](url)

**Comment by ElanHasson** [comment]
@jblestang please move the comment to #290 where the issue is being discussed.
