### ISSUE TITLE
Help with hyperopt

### ISSUE THREAD

**Issue by Tim9889** [gcarq/freqtrade#309]
Is there a forum, telegram channel or something else for asking usage questions in general? 

My problem is that I got stuck with the optimization process using hyperopt. When ever I feed the settings from hyperopt in analyze.py and backtest them, the profits are completely off (mostly losses) compared to the calculations that hyperopt made. 
The wiki did unfortunately not really help/ solve this problem. Could somebody assist me setting it up correctly? 

Thanks in advance for your help!

**Comment by glonlas** [comment]
Hello,

Please refer to the README.md. You will find a link to the Slack channel.
