### ISSUE TITLE
bot keeps thinking order is opened

### ISSUE THREAD

**Issue by carmelo42** [gcarq/freqtrade#319]
Hello,

sometimes, the bot want to sell position. 
But the order is sent to bittrex but not executed, often because when the order arrives on bittrex the price is already lower.

so, I sell myself the order, and the bot keeps thinking he has to sell it ... even after restart !

only way to go out its selling loop is to delete and recreate the tradesv3.sqlite file

**Comment by eliashassing** [comment]
I've run into the same problem. A couple times triggered when I used /forcesell when the bot didn't initiate a sell order (or so I thought), and ended up with an one closed and one open order for the same pair.

**Comment by shusso** [comment]
please re-open if problem still persists 👍
