### ISSUE TITLE
Hyperopt readme, some remarks to make it more clear for noobs

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#335]
Sorry to log something on hyperopt, I was reading this ... and most is clear

https://github.com/gcarq/freqtrade/blob/develop/docs/hyperopt.md

Only not the following
- when I see the result "adx": {"enabled": true,"value": 15.0},.... how do I know when I add this to analyze if we need a > or a < sign? this to me is not clear ([link](https://github.com/gcarq/freqtrade/blob/develop/docs/hyperopt.md#understand-the-hyperopts-result)).  
- in the example link we also see ""green_candle": { "enabled": true}," ... this indicator has no value: how would one add this to analyze? ([link](https://github.com/gcarq/freqtrade/blob/develop/docs/hyperopt.md#understand-the-hyperopts-result)).  
- If there already is a base strategy like for example (A) 
```
         (dataframe['close'] > 0.00001000) &
         (dataframe['cci'] < -90.0) &
         (dataframe['fastd'] < 15) & (dataframe['fastk'] < 15) &
         (dataframe['fastk'] < dataframe['fastd']) &
         (dataframe['adx'] > 15)
```
or example (B) 
```
         (dataframe['macdhist'] > 0) &
         (dataframe['macd'] < 0) &
         (dataframe['macdsignal'] < 0)
```
how would we optimize this?
(in short: would it be OK to share 1 or 2 real examples? how one does this - from strategy =>  testing/using hyperopt => translating it to a new strategy ??)

**Comment by josemariabooymts** [comment]
Ahhh yas

**Comment by glonlas** [comment]
Thank you for commenting on the documentation. The role of the doc is to be clear, if it is not we will update it. Feel free to contribute to it. 

Now to answer your questions:
> when I see the result "adx": {"enabled": true,"value": 15.0},.... how do I know when I add this to analyze if we need a > or a < sign? this to me is not clear (link).

Hyperopt is using only the combination of the rules you have defined in `SPACE` and `populate_buy_trend()` inside `hyperopt.py` file. It totally ignores your strategy in `analyze.py`.

Per default ADX rule is defined in two places:
- SPACE (to explain is there is value to change in the formula or just enable/disable it)
- populate_buy_trend() function (contains the formula hyperopt is using for each rules in SPACE)

In your example, inside SPACE you have:
```python
    'adx': hp.choice('adx', [
        {'enabled': False},
        {'enabled': True, 'value': hp.quniform('adx-value', 15, 50, 1)}
    ]),
```

Then you will find in [populate_buy_trend()](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/hyperopt.py#L167-L207) what is the formula applied to the name 'adx'
```python
        if params['adx']['enabled']:
            conditions.append(dataframe['adx'] > params['adx']['value'])
```
So, you understand that hyperopt had tested `dataframe['adx'] > params['adx']['value']`
Your result was 15.0, it means your new formula should contain: `dataframe['adx'] > 15.0`

> in the example link we also see ""green_candle": { "enabled": true}," ... this indicator has no value: how would one add this to analyze? (link).

Same has previously look inside  your [populate_buy_trend()](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/hyperopt.py#L167-L207) to see what definition for `green_candle`. Today `green_candle` is  `dataframe['close'] > dataframe['open']`.

> If there already is a base strategy like for example (A)

In your case, if Hyperopt only returned `adx` and `green_candle` as  `"enabled": true}`:  your final buy strategy will be:
```python
   dataframe['adx'] > 15.0 &
   dataframe['close'] > dataframe['open'],
```

# Note about Hyperopt
Per defaut hyperopt without the param `-e`or `--epochs` will only do 100 iterations (epochs) to find the best strategy. Means it will change only 100 values for your all parameters combinations. 100 iterations are too few to find the right parameter especially if you have a lot of rules that have variables like in the previous example `adx`.

In develop `adx` is defined like:
```python
'adx': hp.choice('adx', [
        {'enabled': False},
        {'enabled': True, 'value': hp.quniform('adx-value', 15, 50, 1)}
    ]),
```
Means it will test each value between 15 and 50. It means you need at least 36 iterations (epochs) to fully test this only parameter. And this is true is you have only this rule and no other rules to apply.

To do so I am running between 5000 and 10,000 epochs. The hyperopts will compute for many days.

Without MongoDB `python3 ./freqtrade/main.py -c config.json hyperopt  -e 5000`
With MongoDB `python3 ./freqtrade/main.py -c config.json hyperopt  -e 5000 --use-mongodb`

**Comment by Tim9889** [comment]
> To do so I am running between 5000 and 10,000 epochs. The hyperopts will compute for many days.

In my case hyperopt is done after a couple of hours, with -e 5000, without mongodb. From what I read it should take much longer, right? Or is my computer just so much faster?? Using a MacBook Pro from 2016 ... What tells me that the hyperopt was working properly?

**Comment by shusso** [comment]
@Tim9889 if you get hyperopt to report a result, then it is working as expected.

**Comment by shusso** [comment]
feel free to re-open if there are still issues
