### ISSUE TITLE
APIKEY Invalid Params (BTC)

### ISSUE THREAD

**Issue by Aiden-aiden** [gcarq/freqtrade#336]
Status: Got OperationalException:
Traceback (most recent call last):
  File "./freqtrade/main.py", line 82, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 293, in create_trade
    if exchange.get_balance(_CONF['stake_currency']) < stake_amount:
  File "/root/cat/freqtrade/exchange/__init__.py", line 127, in get_balance
    return _API.get_balance(currency)
  File "/root/cat/freqtrade/exchange/bittrex.py", line 88, in get_balance
    currency=currency))
freqtrade.OperationalException: APIKEY_INVALID params=(BTC)

Issue /start if you think it is safe to restart.

I don't why but I'm always getting this error :/

**Comment by glonlas** [comment]
are you using the latest develop branch? I had this issue before when we had the get_signal async.
I looked like a random error from Bittrex.

**Comment by Aiden-aiden** [comment]
Yes that's a fresh clone made few hours ago :/

**Comment by glonlas** [comment]
Please comment on the ticket that is already discussing it : #240
