### ISSUE TITLE
Please add us dollar amount made or loss per trade to sqlite db.

### ISSUE THREAD

**Issue by devalias** [gcarq/freqtrade#343]
Hi, this is not a issue, this is a request.  Please add us dollar amount made or loss per trade to sqlite db.

**Comment by robmoggach** [comment]
In reality this should be fiat as configured in `config.json` not simply USD.  

However it also introduces problems:
* if fiat is changed in the config
* the value is not accurate as fiat is not the trading currency
* Do we also calculate the rate of exchange at buy and sell and the difference? 

If your preference is to trade currency with USD you really should use an exchange that supports USDT trading pairs and request support for that exchange.

**Comment by devalias** [comment]
I like the idea of getting the value from the config file so it can be any currency.  I would like to have the amount in a fiat tracked in the db for profit and losses per transaction.

**Comment by jblestang** [comment]
It has no sense to do this, if you run your bot for a very long time and BTC is up 20% since you started and you’ve not withdrawn anything your balance in USD will be entirely wrong.

**Comment by devalias** [comment]
hi, I see where you are coming from with that explanation.  What I was thinking is capture the dollar amount per transaction in the db for graphing purposes.  To easily see profits/losses in a graph.

**Comment by gcarq** [comment]
I also think this adds too much complexity for what it offers as already mentioned by @robmoggach, but we already store timestamp, rate and amount. So we could implement a helper script which fetches the price for the given timestamp and display it for testing/debugging purposes.

**Comment by shusso** [comment]
I think we are not going to implement this for now.
