### ISSUE TITLE
Installation dependency ta-lib

### ISSUE THREAD

**Issue by robmoggach** [gcarq/freqtrade#348]
On MacOS `ta-lib` is not installed by default.

Documentation should mention that `brew install ta-lib` will install this dependency and should be run before requirements are installed using `pip`.

**Comment by shusso** [comment]
@robmoggach thanks for the issue 👍 
ta-lib is installed with `pip` in the requirements:
https://github.com/gcarq/freqtrade/blob/develop/requirements.txt#L14

**Comment by robmoggach** [comment]
on my system that installs the python library but not the system library -
I had to `brew install ta-lib` first and then the python library would
install normally.

--
Robert Moggach
http://moggach.com
Mobile (647) 544-1793
