### ISSUE TITLE
Support Slack integration

### ISSUE THREAD

**Issue by vertti** [gcarq/freqtrade#35]
Similar commands that are now available for Telegram bot, should be available with a Slack bot.

**Comment by gcarq** [comment]
Added foundation to support multiple messenger integrations with commit: https://github.com/gcarq/freqtrade/commit/3ab14dfe3912f666ff4566da1a92c8507f507a6a

For a basic slack integration following needs to be done:

```
freqtrade/
  rpc/
      __init__.py: add slack to registered modules if enabled
      slack.py: implement init(...), cleanup(...) and send_msg(...) for basic notification support
      telegram.py
      ...
  ...
```

**Comment by shusso** [comment]
closing in favor of #581
