### ISSUE TITLE
Backtesting: No module named 'freqtrade'

### ISSUE THREAD

**Issue by crypdick** [gcarq/freqtrade#365]
```
python -V
Python 3.6.1 :: Anaconda custom (64-bit)

branch develop

git log --format="%H" -n 1
3a902289f11e8d30fa747ee34e40a159333d4ab2
```
When I try any of the python commands in the [backtesting instructions](https://github.com/gcarq/freqtrade/blob/develop/docs/backtesting.md) I get the following error:

```
Traceback (most recent call last):
  File "./freqtrade/main.py", line 15, in <module>
    from freqtrade import (DependencyException, OperationalException, __version__,
ModuleNotFoundError: No module named 'freqtrade'
```

**Comment by shusso** [comment]
@crypdick thanks for the issue 👍  
Before running backtesting have you installed the requirements by issuing the following command per the [install instructions](https://github.com/gcarq/freqtrade/blob/develop/docs/installation.md)
```
pip3 install -e .
```
