### ISSUE TITLE
Pair BTC_DGD is not available at bittrex

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#378]
## Step 1: Have you search for this issue before posting it?

Yes ;)

Jan 13 17:31:00 bitbot python3.6[4339]: validate_pairs(config['exchange']['pair_whitelist'])
Jan 13 17:31:00 bitbot python3.6[4339]: File "/var/www/freqtrade/freqtrade/exchange/__init__.py", line 84, in validate_pairs
Jan 13 17:31:00 bitbot python3.6[4339]: 'Pair {} is not available at {}'.format(pair, _API.name.lower()))
Jan 13 17:31:00 bitbot python3.6[4339]: freqtrade.OperationalException: Pair BTC_DGD is not available at bittrex

## Step 2: Describe your environment

  * Branch: Develop
  
## Step 3: Describe the problem:

Based on error text some pairs are not available at bittrex. But I have never seen this error before. ALso I saw it thrice. Have they cleand up their alt coins? 

The problem is that it is HALTING the bot based on an error, when this should only be a WARNING

### Steps to reproduce:

Add pair like above to whitelist on bittrex
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by jblestang** [comment]
DGD or DGB?

**Comment by seansan** [comment]
According to eror msg dgd (and some more). Essence is warning Vs error

**Comment by jblestang** [comment]
Can you show your config file? Are you specifying the pairs you want to trade?

**Comment by seansan** [comment]
Not behind laptop. But i have whitelist and blacklist.

**Comment by glonlas** [comment]
I agree with @jblestang, it looks like there is a typo in the pair in your config file (`validate_pairs(config['exchange']['pair_whitelist'])`)

**Comment by vertti** [comment]
I think having an invalid config should halt the bot, not just give a warning. So this works as intended.

**Comment by seansan** [comment]
I don’t think this is correct

https://support.bittrex.com/hc/en-us/articles/115003816652-Pending-Market-Removals-1-12-2018

Having a whitelist with 60+ coins. Then buttercup delisted 1. So my config
is fine until date X ... when delisted

Halting the bot is not the solution to this situation. A pair that was ok
before. And gets ddelisted should give a warning at the max
