### ISSUE TITLE
Improve unittests

### ISSUE THREAD

**Issue by vertti** [gcarq/freqtrade#38]
- [x] fix tests that require internet access (some more mocks needed
- [ ] check coverage and implement missing tests
- [x] convert to using Pytest with less nesting

**Comment by gcarq** [comment]
@vertti I added some tests, right now we're at coverage of [79%](https://coveralls.io/github/gcarq/freqtrade?branch=develop)

**Comment by glonlas** [comment]
I think we are not so bad now with [85%](https://coveralls.io/github/gcarq/freqtrade?branch=develop)

**Comment by glonlas** [comment]
We are at 91% this is very good.

**Comment by shusso** [comment]
good job everybody 👍
