### ISSUE TITLE
Can we print what buy/sell signal a particular trade has used to make the buy or sell decision.

### ISSUE THREAD

**Issue by rohit366** [gcarq/freqtrade#380]
@shusso Can we print the buy | sell signal values the BOT had used to make the decision in telegram in case of the dry-run or back-testing phase.

Or just print the value of RSI at the time of buy or sell of any trade. This will help optimize the signal values better.

**Comment by glonlas** [comment]
We can add a log in the terminal. But telegram must stay clean. 
However, your question about adding RSI value is relevant only if the user strategy uses RSI. 

I will suggest to look at `plot_dataframe.py` script and run your backtesting only with this pair to optimize your strategy.

**Comment by vertti** [comment]
No, I don't think we can. The buy and sell signals can be a very complex mix of different indicators and conditions, so the print would need to be manually added to make sense for specifically your strategy.

I encourage you to do what @glonlas suggested and use the plot_dataframe script see how your strategy works visually.
