### ISSUE TITLE
Remove delisted & to be delisted coins from trading

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#382]
## Step 1: Have you search for this issue before posting it

Yes. Similar issue here. https://github.com/taniman/profit-trailer/issues/395

## Step 2: Describe 

Development 
 
## Step 3: Describe the problem:
*Explain the problem you have encountered*

Is this info also in the api? And should we consider adding to be delisted coins to the blacklist?

 —- this way the bot doesn’t pick up on a trend where we know the coin is going to fall because it is going away (and you are stuck with them at -70-80% loss

Problem. Bot buys to be delisted coins. Not smart. Guarantee to lead to a loss. 

Solution. Read info from the coin and if delisted found in api request then skip it. 

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by seansan** [comment]
pull request created; need to find the words "delisted" in notice ... no other way. 

**Question**: Suppose your both runs 10 days. Does the function "refresh_whitelist" then get called say every XX hours? ..... ie what happens if a coin gets delisted or De-actived during the run

**Comment by shusso** [comment]
IIRC the whitelist is being actively refreshed. Feel free to re-open if problem persists.
