### ISSUE TITLE
Print summary of trade signals to explain decisions

### ISSUE THREAD

**Issue by crypdick** [gcarq/freqtrade#384]
I think it would be nice to have the bot summarize the current buy and sell signals, either as a truth table (e.g. rsi < 35: True) or the raw values (rsi = 22.4). These could be used as quick "explanations" for why freqtrade made a given decision. 

If coupled with alerts, I think it would make freqtrade a nice tool to monitor many currencies in real-time for potential opportunities. My trading strategy involves drawing support and resistance lines which I don't think I'd be able to code using TA-lib.

Would accept a PR if I went ahead with the signal summaries?

**Comment by shusso** [comment]
Thanks for the issue 👍  We'll look into this when implementing #290
