### ISSUE TITLE
Add notifications by SMS, email, and Slack

### ISSUE THREAD

**Issue by crypdick** [gcarq/freqtrade#390]
Title says it all. These are already implemented in [crypto-signal](AbenezerMamo/crypto-signal), so we could potentially merge in their code (MIT license). 

See:
https://github.com/AbenezerMamo/crypto-signal/tree/master/app/notifiers
https://github.com/AbenezerMamo/crypto-signal/blob/master/app/notification.py

**Comment by shusso** [comment]
Thanks for the issue @crypdick I created a parent issue #581 lets move the discussion there.
