### ISSUE TITLE
Allow buying and selling via Email [Request]

### ISSUE THREAD

**Issue by thorK65** [gcarq/freqtrade#401]
I was wondering whether buying and selling via email could be implemented as an option. The bot would check an email account and do what the emails request (buy BTC_xxx or sell BTC_xxx). 
By doing so we could use the buy and sell signals and ready made scripts from Tradingview and use the bot bot just for buying and selling.

**Comment by glonlas** [comment]
It could be, but not part of the roadmap. However, relying on another service like Tradingview is not a good solution. It will be too slow and inaccurate with your current state. Tradingview has no idea of your buying price and if you will make a profit or not.

You better to implement the Tradingview logic in your buy and sell strategy. Faster, more reliable.

**Comment by thorK65** [comment]
You are right, but I have a TV scrip where I don't know the source (cause the author is not sharing it) that gives such a great profit I never had with any strategy I used with freqtrade ...
