### ISSUE TITLE
Current Profit % Vs Bought rate

### ISSUE THREAD

**Issue by Thuruv** [gcarq/freqtrade#405]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment

  * Python Version: 3.6
  * Branch: Develop
  * Last Commit ID: a4b8db38cae486c3c8d32de332aded836ba99e35 
 
## Step 3: Describe the problem:

The Bot buys the coin with a price (X). But calculating the current Profit ( on Status & ROI check) with the actual open rate(Y) at the time of buying.

- Bought XRP @ `13600` SATOSHI
- The current bid price is `13390`
- /Status  showing the open rate is` 13599`
- On calculating the current profit %, 
 - If you calculate with the actual bought price, it would be `2.04%`
 - If you calculate with the open rate as shown in the result, it would be `2.03%`

This applies to all the transactions.

![untitled](https://user-images.githubusercontent.com/6994607/35166952-ad70ee88-fd79-11e7-8530-ccec4442765e.png)

**Comment by Thuruv** [comment]
Guys, I  think It's a important bug which affect the sell rate of Low coins.

**Comment by Thuruv** [comment]
@glonlas any help :(

**Comment by shusso** [comment]
feel free to re-open if problem persists.
