### ISSUE TITLE
Add total open trades to /status table

### ISSUE THREAD

**Issue by devalias** [gcarq/freqtrade#410]
It would be nice to be able to see the total open trades when doing a /status table in telegram.
sometimes if you have the bot with lots of open trades it's hard to tell how many at a glance.

**Comment by devalias** [comment]
ok, /count does this already.  it would be nice if this was under /status table.  :)

**Comment by shusso** [comment]
@devalias thanks for the issue 👍
I'm adding a more info about trades on few telegram messages, I fixed this on my [branch](https://github.com/gcarq/freqtrade/compare/feat/telegram-sell-msg) while at it. Will create PR after fixing few tests

**Comment by shusso** [comment]
@devalias fixed in develop

**Comment by devalias** [comment]
thanks
