### ISSUE TITLE
get_signal() missing 1 required positional argument: 'interval'

### ISSUE THREAD

**Issue by glonlas** [gcarq/freqtrade#413]
## Step 2: Describe your environment

  * Python Version: 3.6.3 (`python -V`)
  * Branch: Develop
  * Last Commit ID: d2371b5bac9298e658c4ef2f4a789488ad363547 (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
Since the merge of the PR #391, we can have a bug with get_signal(). Now [get_signal() requires two parameters](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/analyze.py#L284), but in [main.py line 267](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/main.py#L267), and [line 325](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/main.py#L325) get_signal() has only 1 param.

### Steps to reproduce:

  1. Have pair in your config file
  2. Start the bot `python3 ./freqtrade/main.py`
  
### Relevant code exceptions or logs:

  ```
Traceback (most recent call last):
  File "./freqtrade/main.py", line 479, in main
    interval=int(_CONF.get('ticker_interval', "5"))
  File "freqtrade-develop/freqtrade/misc.py", line 83, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 82, in _process
    state_changed = create_trade(float(_CONF['stake_amount']), interval)
  File "./freqtrade/main.py", line 325, in create_trade
    (buy, sell) = get_signal(_pair)
TypeError: get_signal() missing 1 required positional argument: 'interval'
  ```

**Comment by glonlas** [comment]
Should be fixed with the PR #414. Waiting for review and merge.

**Comment by fwFEM** [comment]
Hey Gérald,

just found the same issue some minutes ago, when I took a first run with freqtrade. What do you think about 
```
def get_signal(pair: str, interval: int = None) -> (bool, bool):
```
and thereby simply make a dynamic function. Would result in less needed code changes.

Best,
Felix

**Comment by glonlas** [comment]
The fix is there. You need the interval at least a default. Otherwise, the bot will not know which one to take on Bittrex. 

I think the merge to develop failed.

**Comment by glonlas** [comment]
PR merged. Let me know if you have still troubles.

**Comment by fwFEM** [comment]
Your fix is working for me ;-)

**Comment by shusso** [comment]
fixed in develop
