### ISSUE TITLE
Bittrex : Dust Trade disallowed

### ISSUE THREAD

**Issue by kjbstar** [gcarq/freqtrade#42]
Hi,

I gave a try to your bot this night, but I wanted to play with so little values than I faced the Bittrex anti micro trades thing :)

`Traceback (most recent call last):
  File "./main.py", line 261, in app
    _process()
  File "./main.py", line 62, in _process
    handle_trade(trade)
  File "./main.py", line 147, in handle_trade
    execute_sell(trade, current_rate)
  File "./main.py", line 99, in execute_sell
    profit = trade.exec_sell_order(current_rate, balance)
  File "/home/johan/freqtrade/persistence.py", line 81, in exec_sell_order
    order_id = exchange.sell(str(self.pair), rate, amount)
  File "/home/johan/freqtrade/exchange.py", line 79, in sell
    raise RuntimeError('BITTREX: {}'.format(data['message']))
RuntimeError: BITTREX: DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT`

Maybe the bot should wait (or handle this error) to avoid it to stop.

By the way, I don't know why there was no problem with this limit when he bought...

**Comment by vertti** [comment]
Thanks for the info. I had not seen that error message before. Did you sell at a loss? Because then it could have just bought slightly over the limit and tried to sell with lower than the limit. But you are correct that we should handle that better.

**Comment by kjbstar** [comment]
Hi,

That's right it happened during a sell at loss.

**Comment by shusso** [comment]
Please open if the problem still exists
