### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by martinjoubert** [gcarq/freqtrade#421]
It seems that the binary called freqtrade is not maintained.

Could you please tell me how to build it for mac, and windows?

**Comment by glonlas** [comment]
Which binary? Could you be precise about it?
The Install doc is not working for you? https://github.com/gcarq/freqtrade/blob/develop/docs/installation.md

**Comment by glonlas** [comment]
No answer? I close this ticket. Feel free to reopen it if you still have trouble.
