### ISSUE TITLE
Telegram conflict

### ISSUE THREAD

**Issue by kjbstar** [gcarq/freqtrade#43]
Hi again,

After #42 , I killed the background process and started again the bot. All seems to work well, but I can see this error several times:

`2017-09-29 08:13:10,167 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)`

But the Telegram bot works well. So I don't know what it refers to.

**Comment by gcarq** [comment]
This is because only one instance can register a webhook at the same time. It looks like the telegram servers had some issues and didn't close your old connection properly and caused a conflict.

**Comment by kjbstar** [comment]
Thanks for the info, it's not an issue then, sorry !
