### ISSUE TITLE
matplotlib backend on mac os x

### ISSUE THREAD

**Issue by robmoggach** [gcarq/freqtrade#434]
I ran into this issue trying to render images with the plot scripts on mac os x: https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

Solution works perfectly so some documentation would help to this effect-

**Comment by vertti** [comment]
I will be replacing matplotlib with Plotly soon.

**Comment by shusso** [comment]
Plotly has been taken into use
https://github.com/gcarq/freqtrade/blob/develop/scripts/plot_profit.py
