### ISSUE TITLE
Make the Bot "Plug&Play" - Separate Strategy entirely 

### ISSUE THREAD

**Issue by macd2** [gcarq/freqtrade#440]
Feature Request:

how about separating the botcode entirely from the starts?

So for each strat there is a folder: 

`/user_data/STRATNAME/`

in this folder we have all the strat needs to run like:
`The strat.py file + the database for this strat`
and than we remove the `/freatrad/config.json` file and integrate entirely in to the strat.py file 
 
All we need is ` python3 ./freqtrade/main.py --strategy FOLDERNAME`
Like this we could run multible live strats with the same bot code

A nice addition would be to move the path to desired `/testdata/testset1` in to the `/user_data/FOLDERNAME/STRATNAME.py`

**Comment by shusso** [comment]
closing in favor of #435
