### ISSUE TITLE
Manual buy in telegram

### ISSUE THREAD

**Issue by devalias** [gcarq/freqtrade#442]
Hi, this idea would be nice, "Buy command for telegram? #214" but instead of putting in the amount use the amount already specified in config.json so it would look like:  /buy XRP for example.

**Comment by shusso** [comment]
thanks for the issue @devalias 👍 I don't think there is any still a plan to support manual trading in the bot

**Comment by vertti** [comment]
Buying is strictly tied to selling in how well the bot behaves. You could for example buy manually and due to the sell signal, bot could sell it instantly. All in all, I don't think manual buys have a place in frequency trade bot.

**Comment by devalias** [comment]
thanks for the explanation.
