### ISSUE TITLE
Support for binance

### ISSUE THREAD

**Issue by bjolivot** [gcarq/freqtrade#447]
This is not a bug, just info about new exchange dev.
I find this bit very promising and want to add my prefered exchange.
You will find my work in progress here :
https://github.com/bjolivot/freqtrade/tree/binance

If someone care to help, you are welcome.

I will use this thread for questions too as I'm no expert in python3.6 nor with bittrex ^^

Here we go.

In the get_ticker_history function how many ticker are expected (default is 500 on binance) ?
Have you any specific config on travis ?

**Comment by jbweb** [comment]
Nice, i was trying this myself, but found it to be to complex for without any Python knowledge.
Unfortunately Bittrex doesn't support new registrations for more then a month now. Binance is open again, so will be a good alternative.

I found some minor issues on your fork, but can't report them in your repository. Maybe you can open this so more people can contribute?

**Comment by shusso** [comment]
I think the plan is to support binance, and others, using ccxt per #230

**Comment by kryofly** [comment]
I'm wonder if an homegrown solution can benefit on binance/bittrex, due to lack of websockets in ccxt.

**Comment by bjolivot** [comment]
any work allready done with ccxt ?

**Comment by glonlas** [comment]
It will start this weekend. I think about pushing a branch for it. So you can contribute with PRs

**Comment by shusso** [comment]
> I'm wonder if an homegrown solution can benefit on binance/bittrex, due to lack of websockets in ccxt.

@kryofly less code we have to maintain the better imho..

**Comment by kryofly** [comment]
@shusso Yeah, I was looking at:
https://github.com/sammchardy/python-binance

But still considering using that as some kind of module, it seems to requrire alot of rewiring due to need of giving up control from freqtrade-mainloop to a twisted-loop.

Still websockets is the future :D

**Comment by jbweb** [comment]
@glonlas Can't wait, please post when a branch is created, so i can try/test actively with some friends using Bittrex. Love to see the difference and maybe we can post feedback..

**Comment by bjolivot** [comment]
@glonlas don't hesitate to post early work, I can fill the blanks :)

**Comment by glonlas** [comment]
Binance will be supported when this PR will be merged: #489

**Comment by shusso** [comment]
we are moving to ccxt which will add support for binance

**Comment by bulentongun** [comment]
Are we ready for margin trading in Binance?
https://www.reddit.com/r/CryptoCurrency/comments/bjlto5/margin_trading_flag_enabled_for_9_trading_pairs/

**Comment by xmatthias** [comment]
currently pretty sure not (out of the box).
depending on how it's done, it might be easy to add.

However, how to create a margin trade is not yet documented [api docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md).

Feel free to open an issue once the documentation is updated.

**Comment by azharuniverse** [comment]
@Binance margin trading support +1

By when can we expect ccxt to support this?

**Comment by xmatthias** [comment]
@azharuniverse you should ask this question in the [ccxt repository](https://github.com/ccxt/ccxt/), since it's out of our control

**Comment by fbport** [comment]
CCXT was recently upgraded with Margin orders:

[](https://github.com/ccxt/ccxt/issues/5535#issuecomment-534381993)

**Comment by fbport** [comment]
But how use it?

**Comment by fbport** [comment]
But, how use it?

**Comment by xmatthias** [comment]
I assume you currently can't (without looking at this in detail - but it's something that'll require calling custom methods only available to binance).

it'll take some work to get this implemented into freqtrade, and if someone implements it, it will probably be limited to Binance only, since it's not unified in ccxt (which would make it accessible for other exchanges too).

This creates a lot of extra work, a lot of custom code, custom documentation and custom properties that only work for one specific exchange (binance, in this case).

Feel free to open a new issue requesting this (this issue is about something else entirely) - but don't expect it to be implemented soon by the team - unless someone volunteers to implement this and creates a PR (which will obviously require tests, since we'll need to maintain this in the future).
