### ISSUE TITLE
service file not working

### ISSUE THREAD

**Issue by robmoggach** [gcarq/freqtrade#448]
The latest commits have broken the systemd service file. With some debugging and modification it works. `user_data` is one culprit and also not installing as a module makes it tricky. I was able to workaround but it's not ideal:

### Workaround

Copy `freqtrade` script to your virtualenv bin dir. In my case:

`cp /home/freqtrade/freqtrade/bin/freqtrade /home/freqtrade/freqtrade/.env/bin/`

Make the following adjustments:

#### `~/.config/systemd/user/freqtrade.service`

```systemd
[Unit]
Description=FreqTrade Daemon
After=network.target

[Service]
WorkingDirectory=%h/freqtrade
ExecStart=/home/freqtrade/freqtrade/.env/bin/freqtrade --dynamic-whitelist 50
Restart=on-failure
EnvironmentFile=/home/freqtrade/freqtrade.env

[Install]
WantedBy=default.target
```

#### `~/freqtrade.env`

````
PATH=/home/freqtrade/freqtrade/.env/bin:/usr/local/bin:/usr/bin:/bin
PYTHONIOENCODING=utf-8
PYTHONPATH=/home/freqtrade/freqtrade
VIRTUAL_ENV=/home/freqtrade/freqtrade/.env
````

**Comment by glonlas** [comment]
Thank you for this detailed report. I haven’t use this feature before. I will look how to make it compatible.

**Comment by robmoggach** [comment]
Further to the above - it is possible to use instantiated service files to allow for multiple bots being controlled with one service file...

it let's you do `systemctl --user start freqtrade@bear` or `systemctl --user start freqtrade@macdip` - the file is named `freqtrade@.service` the `@` being how systemd recognized instantiated services and within the `%i` is the instance name (macdip, bear, etc)

This file is named `freqtrade@.service` and would look something like this:

```
[Unit]
Description=freqtrade %i daemon
After=network.target

[Service]
WorkingDirectory=%h/%i
ExecStart=/home/freqtrade/freqtrade/.env/bin/freqtrade -s %i --dry-run-db
Restart=on-failure
EnvironmentFile=/home/freqtrade/%i/systemd.env

[Install]
WantedBy=default.target
```

We really need a working python module with `user_data` abstracted...

**Comment by gcarq** [comment]
Thanks for reporting this, I can take a look as I'm also using this feature, but as you already mentioned we should improve the `user_data` abstraction first.

**Comment by shusso** [comment]
please re-open if problem still persists 👍
