### ISSUE TITLE
Bot suddenly stops watching (and trading)

### ISSUE THREAD

**Issue by kjbstar** [gcarq/freqtrade#46]
Hi again :)

I was wondering why this morning the bot stopped to answering to Telegram commands. So I let a terminal opened, and I just seen that after only 40 minutes, log output just stopped:

> 2017-09-29 16:26:45,327 - analyze - DEBUG - buy_trigger: 2017-09-29T14:20:00 (pair=BTC_GUP, signal=False)
2017-09-29 16:26:45,328 - root - INFO - Got no buy signal...
2017-09-29 16:26:50,901 - __main__ - DEBUG - Handling open trade Trade(id=1, pair=BTC_MUE, amount=20.655822359927708, open_rate=3.873e-05, open_since=closed) ...
2017-09-29 16:44:12,936 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
2017-09-29 16:45:52,386 - rpc.telegram - INFO - Executing handler: _status for chat_id: 414727740

As you can see, line 3 is at 16h26, then line 4 at 16h44.
Last line is a successful attempt to send a command in Telegram. So the script is not terminated as I got answer in Telegram, but it just stop trading.

For info, I have only 7 coins in config.json, and I interrupted and started again with no problem.

**Comment by vertti** [comment]
It's a curious one. I've encountered the same. But as there is no error messages it's a difficult one to debug. I just updated (d045116297289d23395f1e67a7f6d1a962531840) the develop branch to the latest Telegram library which claims to fix a lot of bugs, including something that sounds like the issue we have been encountering. Let's see if that would help.

**Comment by kjbstar** [comment]
That's right, without message, it's hard to guess what happened.
I updated the Telegram library, wait and see :)

**Comment by gcarq** [comment]
I'm closing this because it looks like a temporary timeout issue. If it happens again feel free to reopen this issue
