### ISSUE TITLE
'Pair {} is not available at {}'.format(pair, _API.name.lower()))

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#470]
last commit @ develop e6c215104f7be5bb668830008c9a0792e9fdff21

bitbot python3.6[4431]: 2018-01-29 13:27:13,493 - freqtrade - ERROR - Got fatal exception!
bitbot python3.6[4431]: Traceback (most recent call last):
bitbot python3.6[4431]: File "/var/www/freqtrade/freqtrade/main.py", line 526, in main
bitbot python3.6[4431]: init(_CONF)
bitbot python3.6[4431]: File "/var/www/freqtrade/freqtrade/main.py", line 436, in init
bitbot python3.6[4431]: exchange.init(config)
bitbot python3.6[4431]: File "/var/www/freqtrade/freqtrade/exchange/__init__.py", line 60, in init
bitbot python3.6[4431]: validate_pairs(config['exchange']['pair_whitelist'])
bitbot python3.6[4431]: File "/var/www/freqtrade/freqtrade/exchange/__init__.py", line 84, in validate_pairs
bitbot python3.6[4431]: 'Pair {} is not available at {}'.format(pair, _API.name.lower()))
bitbot python3.6[4431]: freqtrade.OperationalException: Pair BTC_APX is not available at bittrex

>> This happens when a PAIR is in your whitelist, but it does no longer exist on bittrex

Should freqtrade check for existance of pairs before doing the whitelist check? and just ignore the pairs that it does not know

nb. Actually has a relationship with the pull request regarding being delisted. These coins were reported to being delisted before ...

**Comment by shusso** [comment]
doen't look good https://bittrex.com/Market/Index?MarketName=BTC-apx

**Comment by seansan** [comment]
This is how we run
`/var/www/freqtrade/.env/bin/python3.6 /var/www/freqtrade/freqtrade/main.py --dynamic-whitelist 50 --strategy currentstrategy`

Can it be that it is checking a pair defined in the conf whitelist that does no longer exist on bittrex?

**Comment by shusso** [comment]
@seansan seems that it got removed https://support.bittrex.com/hc/en-us/articles/115003977472-Pending-Market-Removals-1-26-2018

**Comment by seansan** [comment]
Yes I understand, see my referene to delisted coins pull request. 

But even so. Freqtrade should handle this situation ... now it crashes the bot completely

**Comment by shusso** [comment]
feel free to re-open if problem still persists
