### ISSUE TITLE
 WARNING - Too old dataframe for pair 

### ISSUE THREAD

**Issue by macd2** [gcarq/freqtrade#475]
## Step 1: Have you search for this issue before posting it?
yes

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/gcarq/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _3,6.4_ (`python -V`)
  * Develop
  * Last Commit ID: __0bf56f249a74a7eaad153a0f4e12748e2f138aeb___ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
*Explain the problem you have encountered*
Getting:
Too old dataframe for pair

**Comment by jblestang** [comment]
What ticker interval are you using?

**Comment by macd2** [comment]
i happens with any ticker Intervall. 
But usually i use 1, 5 or 60min 

I also noticed now that at the beginning i get the warning only for a view pairs but over time the message appears for all pairs so maybe something with the download or storing of the ticker is wrong?

**Comment by shusso** [comment]
reporting that this is still an problem. I think @vertti added some debugging logs to see how old data we are talking about.

**Comment by gcarq** [comment]
I don't think there is much more we can do. This is a known bittrex issue and hasn't been fixed yet
