### ISSUE TITLE
Add commands helper in the bot

### ISSUE THREAD

**Issue by kjbstar** [gcarq/freqtrade#48]
_Okay it's not an issue, but I don't know how to make a pull request and link my changes, and I don't want to push badly, even in develop branch._

Just wanted to add the bot's commands... In a /help command !
Maybe useful for other people.

Hopefully, changes are very simple.

Add line 49 of telegram.py:

`CommandHandler('help', _help),`

Then, add after performance definition command (for example):

> @authorized_only
def _help(bot: Bot, update: Update) -> None:
    """
    Handler for /help.
    Show commands of the bot
    :param bot: telegram bot
    :param update: message update
    :return: None
    """
    message = """
*/start:* `Starts the trader`
*/stop:* `Stops the trader`
*/status:* `Lists all open trades`
*/profit:* `Lists cumulative profit from all finished trades`
*/forcesell <trade_id>:* `Instantly sells the given trade (Ignoring minimum_roi).`
*/performance:* `Show performance of each finished trade grouped by pair`
    """
    send_msg(message, bot=bot)

When you send `/help` in your Telegram bot, you receive all available commands.

And because I suck with markdown formatting, I add the modified telegram.py (renamed with .txt extension).

[telegram.txt](https://github.com/gcarq/freqtrade/files/1346420/telegram.txt)

**Comment by vertti** [comment]
Fixed in #77 . Thanks.
