### ISSUE TITLE
Selling before buying in poor server conditions 

### ISSUE THREAD

**Issue by jblestang** [gcarq/freqtrade#480]
## Problem encountered :

*in poor server conditions selling should be prioritized over buying*

In poor server conditions we try/catch any errors that occurs while getting results from the server. In poor server conditions this will fail early while searching for buy opportunities without trying to
Sell open trades. We should reverse the logic to first sell then buy if possible.

**Comment by glonlas** [comment]
Look you have fixed it with your PR. Should we close this issue or do you expect more work?

**Comment by jblestang** [comment]
This PR is for another issue. Without this PR when bittrex is having difficulties to answer to all your request it will fail early trying to find a but opportunity rather that trying to sell your open trades. 
This PR reverse the logic so that we sell before we buy (buying can wait, selling should not :)

**Comment by jblestang** [comment]
Yes you're right ... close the issue ...
