### ISSUE TITLE
Need for influxdb backend ?

### ISSUE THREAD

**Issue by bjolivot** [gcarq/freqtrade#483]
Hello,
for another project I used influxdb backend for ohlcv storage.

Benefits: 
 - could easy query any interval
 - could use same backend with multiple bot
 - could use dedicated/singleton process to get data
 - collect/query data for multiple exchange
 - reduced storage (every 1min candle for every pair since binance exists < 250MB)

Is there any need for that in freqtrade ?

**Comment by vertti** [comment]
For what we currently use database for (trade information), any trivial solution works. We don't store  any ticker data currently, for our bots purposes storing ticker history in memory has worked fine so far. But it might change in the future. But let's consider this when we have a clear use case for it.

Btw, how did you get all ohlc info for the whole history? Bittrex is annoying and only gives 5min ticker info for roughly a month and not more.

**Comment by bjolivot** [comment]
at the moment, I only use Binance. The API is providing full history but it takes time to grab, that's why I use more persistent backend.

**Comment by kryofly** [comment]
Just throwing out an idea.
The OHLC format is kind of useless in an 24h market.
Also it is missing the order of H/L.
I've used ordered HL's to better draw pivots. Though how to present them in a dataset or on disk isn't that obvious.
By order I mean the single-bit information if High occured before Low.

**Comment by shusso** [comment]
lets re-visit this in the future
