### ISSUE TITLE
Make Bot automaticaly restart after getting APIKEY_INVALID

### ISSUE THREAD

**Issue by macd2** [gcarq/freqtrade#505]
* Python Version: ___3.6__ (`python -V`)
  * Branch: Develop
  * Last Commit ID: 2765ee5a8527e62e0364b98a1866ea89fa87e879

 Make the Bot restart after getting:  `freqtrade.OperationalException: APIKEY_INVALID`
Currently the bot stops working after this error. Ideal would be a "restart/retry in 30sec" function.

**Comment by seansan** [comment]
Dupe of https://github.com/gcarq/freqtrade/issues/240

**Comment by shusso** [comment]
closing per #240
