### ISSUE TITLE
Exceeding bittrex requests

### ISSUE THREAD

**Issue by andremog** [gcarq/freqtrade#51]
It seems Bittrex does not allow ' too many' API requests. Any way to get around this?

> Traceback (most recent call last):
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
>     self._validate_conn(conn)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
>     conn.connect()
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
>     ssl_context=context)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
>     _context=self)
>   File "/usr/lib/python3.5/ssl.py", line 752, in __init__
>     self.do_handshake()
>   File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
>     self._sslobj.do_handshake()
>   File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /api/v1.1/public/getticker?market=BTC-SYNX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:645)'),))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/bin/freqtrade", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/bin/freqtrade", line 4, in <module>
>     main()
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/freqtrade/main.py", line 269, in main
>     app(_CONF)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/freqtrade/main.py", line 249, in app
>     _process()
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/freqtrade/main.py", line 57, in _process
>     handle_trade(trade)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/freqtrade/main.py", line 137, in handle_trade
>     current_rate = exchange.get_ticker(trade.pair)['bid']
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/freqtrade/exchange.py", line 105, in get_ticker
>     data = _API.get_ticker(pair.replace('_', '-'))
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/src/python-bittrex/bittrex/bittrex.py", line 186, in get_ticker
>     return self.api_query('getticker', {'market': market})
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/src/python-bittrex/bittrex/bittrex.py", line 131, in api_query
>     return self.dispatch(request_url, apisign)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/src/python-bittrex/bittrex/bittrex.py", line 70, in using_requests
>     headers={"apisign": apisign}
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/requests/api.py", line 72, in get
>     return request('get', url, params=params, **kwargs)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/requests/api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/amg/Downloads/freqtrade4/freqtrade-develop/.env/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /api/v1.1/public/getticker?market=BTC-SYNX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:645)'),))
> 2017-10-04 14:27:43,612 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
> ^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
>     t.join()
>   File "/usr/lib/python3.5/threading.py", line 1054, in join
>     self._wait_for_tstate_lock()
>   File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
>     elif lock.acquire(block, timeout):
> KeyboardInterrupt
>

**Comment by conorfennell** [comment]
@andremog unfortunately could not find a way to contact you privately. But you are exposing your api key with those logs.

**Comment by andremog** [comment]
Oh, thanks. I just erased the logs. They were not really needed to understand this issue. Thanks.

**Comment by gcarq** [comment]
Unfortunately there is no way around their rate-limit, they also don't mention how many requests you can do [(src)](https://bitcoin.stackexchange.com/questions/53778/bittrex-api-rate-limit). Nevertheless you should be save with `"max_open_trades": 5`.
Could you append the logs again please (w/o sensitive information)

**Comment by andremog** [comment]
I will try to replicate the error and post the logs (I do not have the old ones anymore). As far as I remember, I got it when I set `"max_open_trades": 1`. Will keep you posted.

**Comment by andremog** [comment]
Just included a similar error.

**Comment by gcarq** [comment]
This should be fixed with the latest released version
