### ISSUE TITLE
binance  Account has insufficient balance when selling 

### ISSUE THREAD

**Issue by dpblnt** [gcarq/freqtrade#528]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/gcarq/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _3.6.3____ (`python -V`)
  * Branch: Develop
  * Last Commit ID: 56e6c563aa1812be9bb79f048f37a7a5b5f2d681
 
## Step 3: Describe the problem:
*The bot bought and was not able to sell the same amount*

### Steps to reproduce:

  1.  let the bot buy
  2. let the bot sell what it bought
  3. _____
  
### Observed Results:

  * What happened?
bot failed to sell : Account has insufficient balance for requested action
  * What did you expect to happen?
to have buy fee calculated in the sell amount
### Relevant code exceptions or logs:

  ```
freqtrade.OperationalException: APIError(code=-2010): Account has insufficient balance for requested action. params=(ETH_WTC, 0.025309, 0.79)

  ```

Total balance of WTC 0.78921000
i see  0.79 WTC bought in the order log (0.01 and 0.78)
fees 0.00078000 and 0.00001000

**Comment by dpblnt** [comment]
I just found the fee in the sqlite db
2|BINANCE|ETH_WTC|1|0.001|0.025213|||0.02|0.79|2018-02-26 15:45:10.317785||

**Comment by shusso** [comment]
@dpblnt thanks for the issue, if you are running a version from a branch that is still developed, please report issues in the open PR

**Comment by dpblnt** [comment]
Thank you for the answer. 
I am using an open PR, I have reported there too.

**Comment by mouhamed-o** [comment]
HI,
i'm new on freqtrade and i get this mesage in log when the bot try to sell coins. "Account has insufficient balance for requested action."
my exchange : Binance
