### ISSUE TITLE
Picking wrong buy signals (custom strategy)

### ISSUE THREAD

**Issue by suraj-miha** [gcarq/freqtrade#533]
## Environment :

  * Branch: Develop
 
## Step 3: Describe the problem:
*Not picking the buy signal (from strategy) precisely*
  
### Observed Results:

  * What happened? 
Sometimes when the bot buys a coin, it does not quite match with the strategy given.
I have observed this several times with bollinger bands and RSI and few other indicators.
  * What did you expect to happen?
Bot should follow the strategy and take the buy signal only when it matches with all the parameters.

### Relevant code exceptions or logs:

  ```
 dataframe.loc[
            (
                (dataframe['rsi'] < 30) &
                (dataframe['fastd'] < 25) &
                (dataframe['adx'] > 35) &
                (dataframe['bb_lowerband'] > dataframe['close'])
            ) ,
            'buy'] = 1
  ```

In above case bot should buy only if all the conditions are true whereas sometimes it buys when RSI is way higher than 30 and candle's 'close' value is greater than bollinger's lower band. I have also noticed this behavior with other indicators. Am I missing something here?

**Comment by vertti** [comment]
I'm seeing very different results from backtesting and production running the bot. I'm not sure if this is related but we need to investigate this more.

Do note that the `bb_lowerband` you are using is calculated from typical price, not close price, so it's not your typical bollinger bands. But if this happens with other indicators also, then we need to be able to reproduce the case and find a reason for it.

**Comment by dpblnt** [comment]
Me too here. 
I have a strategy that produces 77% profit in the last 20 days, using 30min ticker, buy signal is price crossing bb_lowerband, and some guards.

When went live worked for a while, but then suddenly it bought above BB middle, closeer to bb_upperband, then I stopped it. Still trying to sell that coin. 
It's stopped for some days now, and don't know what to look for, how to fix it.

The only thing I could think of is the 30min ticker. I guess it's watching the last candle growing or shrinking, and that messes BB up somehow, but I'm not sure.
I may give up and use the 1min ticker strategy, with 11% profit, if reliable.

Or is there a way to use 2 tickers? a 30 min and a 1 min? Or could I simulate the 30min ticker data from the 1 min ticker data (and feed qtpylib.bollinger_bands with that)?

**Comment by dpblnt** [comment]
Here is my test:
30 min ticker
the buy signal should be triggered by this:
```python
(qtpylib.crossed_below(  dataframe['close'], dataframe['bb_lowerband']*(1- 0.0002) ))
```
dry run buy triggered, the log
```bash
2018-03-21 16:39:14,651 - freqtrade.rpc - INFO - *BINANCE:* Buying [ETH/VEN](https://www.binance.com/indexSpa.html#/trade/index?symbol=VEN_ETH) with limit `0.00658717 (0.098808 ETH, 0.000 USD)` 
```
shot from the trade, BB with same parameters as in freqtrade, cursir at buying point
![Image of screenshot](https://image.ibb.co/gJTZhx/Screenshot_20180321_164944.png)

**Comment by jblestang** [comment]
Maybe a debug mode where we dump as a json file the dataframe when buying/selling, and make the plotting script read this file?

**Comment by dpblnt** [comment]
Yes, that would be very nice. I don't know how to do that. 
I could'n find that debug mode, so I'm printing the dataframe values in from the strategy into a log file and analyse it by hand.

**Comment by dpblnt** [comment]
Another mistaken buy has been triggered in dryrun here
```bash
2018-03-22 10:10:03,224 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=1, pair=ETH_DASH, amount=0.65000000, open_rate=0.76862000, open_since=just now).
```
dataframe[999]
```table
close                                     0.76723
high                                      0.76723
low                                       0.76501
open                                      0.76723
date             2018-03-22 10:09:59.999000+00:00
volume                                      0.095
adx                                       19.3676
fastd_rsi                                       0
fastk_rsi                                       0
bb_lowerband                              0.76676
bb_middleband                            0.768933
bb_upperband                             0.771106
```
shot from the trade, BB with same parameters as in freqtrade, cursor at bb_lowerband of freqtrade
![Image of screenshot](https://preview.ibb.co/iKZWCx/Screenshot_20180322_101517.png)

Looks like the BB implementation is to blame.
bb_lowerband  is 0.76676, while it should be around 0.7575

**Comment by vertti** [comment]
If you are using the bollinger bands from default strategy, do note that it's not your default bollinger bands. The code is 
```
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
```

this uses the typical price instead of close price. If you want normal bollinger bands, change it to:

```
        bollinger = qtpylib.bollinger_bands(dataframe['close'], window=20, stds=2)
```

**Comment by skhalsa10** [comment]
I don't think this is the solution to the Bollinger issue.  There is a precision thing going on with pandas latest version. The actual formula for Bollinger Bands uses typical price not close price
