### ISSUE TITLE
How is looking make orders in freqtrade? 

### ISSUE THREAD

**Issue by xFFFFF** [gcarq/freqtrade#544]
Can anyone compare a freqtrader to Gekko? Mainly I mean algo about adding order to exchange. Does the bot use the ask / bid price? I had a problem with the gecko because my orders were filled with a few minutes delay. The reason was the large discrepancy in prices which in reality were in the order book. Does freqtrade have a more advanced algorithm that defines the price when ordering?

**Comment by jblestang** [comment]
The bot is using  the last known bid/ask price.

**Comment by hashtagex** [comment]
What's up XF, see you on the gekko discord. FYI thanks for the great repo. Using a lot of your info live on poli and Bitfinex. Thankxxx: )

As to freqtrade, it is giving me more profit than gekko has as of yet. Still working on a better strat but last five days running live freqtrade I'm avg around 5% grobe estimate per day. 

But once I get a better strat running it can be more. I like it better than gekko so far. 

FYI running the binance branch of freqtrade live also with +% profit last two days.

**Comment by shusso** [comment]
Feel free to re-open if needed 👍

**Comment by xFFFFF** [comment]
@hashtagex can You pm me on Gekko's discord? I have some questions about freqtrade :)

**Comment by Heerpa** [comment]
Might it be helpful to be able to slightly alter the price used from the last ask/bid? Say you anticipate a rise and want to buy, chances the deal is closed are higher with a higher price. You sacrifice some of the profit but increase the probability to actually make it. #

**Comment by xmatthias** [comment]
wouldn't a configurable option to use market orders instead make more sense? so if you want to use a slightly higher price, you set "usemarket" to true? (this does not exist yet!)

**Comment by Heerpa** [comment]
True, that makes sense. I'd be happy to help with the implementation, but would need some guidance as I don't have a good overview over freqtrade yet.
