### ISSUE TITLE
Care to share a profitable custom strategy?

### ISSUE THREAD

**Issue by cofibit** [gcarq/freqtrade#579]
Have tried building custom strategy from simple moving averages and macd to candlestick patterns but still the end result is still a loss. I am probably doing it wrong but has anybody created a strategy that give decent profits using freqtrade? I hope someone can share their strategy or point me to the right direction what config and strategy to build that would return decent profit.

TIA

**Comment by hashtagex** [comment]
I can give you a little sneak after work when I get a moment. 
3 days live / 29 trades / 17.9% ROI on closed trades.

**Comment by cofibit** [comment]
@hashtagex thanks allot in advance I know freqtrade has a potential it's just that I couldn't find the right strategy/setup for it even though I had tried to make it to work with all the TA I know off.

**Comment by shusso** [comment]
This discussion could be moved to slack where there is a `#sharing-strategies` channel
