### ISSUE TITLE
Cython implementation? (Possible backtesting features? W/Database and C.)

### ISSUE THREAD

**Issue by MoonGem** [gcarq/freqtrade#580]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/gcarq/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * 3.6.5
  * Branch: Develop
  * Last Commit ID: Latest
 
## Step 3: Describe the problem:
Slow hyperopt optimization.

### Steps to reproduce:

1. Lots of coins
2. Lots of timeframes
3. --all
  
### Observed Results:

Python hyperopt parameter optimization is extremely slow.

### Relevant code exceptions or logs:

  ```
~5-12 hours for 5000 epochs on 20 coins. --all
  ```

I was curious, is it possible to implement cython: I read you can do something like this:

import pyximport; pyximport.install()

Wondering, if I can mod hyperopt or maybe even write custom code to analyze backtests and grep the data into a database somehow using cython, or atleast, if you spawn like 32 workers on backtesting.py/submodule you can just bash script 32 instances that will randomize the parameters for you given you let them all become input variables into main.py backtesting (or you would need to sed the file manually)

In short, is this doable? Cython c compiling import + accepting all the values through command line into default_strategy.py? There seems to be a lot of if() statements in the test_strategy.py (mentioned earlier in it's history through github that was removed.)

Seems easy enough. You can parallelize this using gnu parallel to limit your bash script processes given you are allowed command line options. This seems more solid than using hyperopt or ray.

From research, hyperopt has no plans to become threaded, and at that, hyperopt did not work when run against fmin(MongoTrials())

Infinte loss. Not sure why. 

Cython can speed up the process by half. And then thread manually and just force mongodb implementation to throw the data into the database and return the best profit parameter. Backtesting many coins with great length is key to optimization, and you'll need speed increase and solid code to get solid results.

This is something I'm willing to try and code if available to cython on the backtesting module, but, how can I implement command line arguments passed into the strategy submodule? If you can provide me with a quick example and are interested we can move hyperopt out of the picture (because it's beyond buggy)

my best guess is just a bunch of if statements and numbers 0 for on 1 for off on each parameter and trigger, and then variable trigger options. But I really don't want to code this in bash, as, this can be done in python as a piece of cake. 

In short, I'd like to optimize the threading parts of the bot, and rip out hyperparameter and make a bunch of mongodb calls to insert results and pull the best profiting result when the epochs are done running. Sounds very easy and beneficial at first thought. Just add some command line paremeters to current code, and a Popen function, some mongodb DB inserts and query, import the cython builder and done right? Is there a way to limit Popen calls? Say, call Popen when a thread closes for the next parameter?

Any thoughts/comments/advice?

I was also thinking, since triggers are simply triggers, optimizing the greater or less than symbols in the strategy params with a few more if statements. This could possibly be beneficial. But overall, I'm impressed by the speed of the bot, could easily plow through 100-200K backtests in a day with this code.

**Comment by shusso** [comment]
@MoonGem thanks for the issue 👍 
I'm pretty sure none of the core-members will take a stab at Cython. The work required for that is going to be pretty immense. Obviously, I can be wrong but that's just my gut reaction. If you feel like taking a stab go ahead.

> Cython can speed up the process by half

But at what maintenance and complexity cost?

> Python hyperopt parameter optimization is extremely slow.

It is slow because the search space is, quite franky, pretty big :)

> how can I implement command line arguments passed into the strategy submodule?

You can find a argparser document [here](https://pymotw.com/2/argparse/) or look how we do it [here](https://github.com/gcarq/freqtrade/blob/62a3366fbfa705591f2e46880f4d359c170dde4c/freqtrade/arguments.py)


@vertti has been optimizing the backtesting code and has gotten huge speed improvements just by fixing code that has been making unnecessary string conversions etc.

**Comment by MoonGem** [comment]
Good points :)
