### ISSUE TITLE
debuglevel (-v) not working correctly for backtesting

### ISSUE THREAD

**Issue by xmatthias** [gcarq/freqtrade#583]
## Step 2: Describe your environment

  * Python Version: 3.6.4 (`python -V`)
  * Branch:  Develop
  * Last Commit ID: a2c3df3ac5e353b1bd69a0269bd252760f5a6b3b
 
## Step 3: Describe the problem:
starting backtesting with -v does not output all log messages

### Steps to reproduce:
1. start backtesting (`python freqtrade/main.py -v backtesting --export trades --realistic-simulation  --refresh`
2. observe output - debug-messages for download_backtesting_testdata are not shown (Current start/stop)

### Observed Results:

* expected Logs for download_backtesting_testdata do not show
* Expected to see the following messages, but they were not outputted. https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/__init__.py#L149-L150

* the problem was introduced with objectify, was working fine before that.

### Relevant code exceptions or logs:
The problems seems to come from the initialization of loger without parameters (initializing with INFO as default) - overwriting the -v setting.

https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/__init__.py#L13

**Comment by gcarq** [comment]
I'm able to reproduce this. I think we should fall back to `logging.getLogger().getEffectiveLevel()` if no explicit loglevel was passed to the constructor

**Comment by xmatthias** [comment]
#584 fixed this, thanks for the quick fix!
