### ISSUE TITLE
All balances are zero | Invalid response from Bittrex

### ISSUE THREAD

**Issue by legendsneverdiejp** [gcarq/freqtrade#610]
## Describe your environment

  * Python Version: Python 2.7.12 (python -V) | Python 3.5.2 (python3 -V)
  * Branch: Develop
  * Last Commit ID: 49f2c246984a651e0c0a568c32d69d53d6531c03
 
## Describe the problem:
Issue 1:
After a fresh bot installation, which by default is set to dry_mode to run as demo without real tradings, the balances are zero, so it just runs without any real time testing.

Issue 2:
Invalid response from Bittrex params=(BTC_ZEC), retrying in 30 seconds...
This is happening almost permanently and with other pairs too, not just btc_zec

### Steps to reproduce:
Issue 1:
  1. install fresh bot
  2. call /balance in telegram
  3. answer is 'All balances are zero.'

Issue 2:
  Just let the bot run for a while.
  
### Observed Results:
Issue 1:
  * What happened?
No balances returned.
  * What did you expect to happen?
I expect that if is a clean installation, and on dry_mode, bot should have pre set some balances to be able to show real trading operative. e.g have 1 btc and 500$ by default.

Issue 2:
  It should grab latest values from exchange without getting invalid responses.

**Comment by xmatthias** [comment]
for issue 1:
this is expected behavior - in dry-mode it does not require (nor use even if provided) your keys, so you are 100% sure nothing in the exchanged is touched.
if you want to have /balance working without starting the bot, try to set ` "initial_state": "stopped",` in your configuration, but `"dry_run": false,`.

**Comment by shusso** [comment]
Thanks for the issues @legendsneverdiejp 

issue 1: we don't support `demo` mode. `dry_run` should behave as realistic as possible (without touching your currencies) and I don't see the need to have those either.

issue 2 is known, and is one of the motivations on getting `ccxt` into use.
