### ISSUE TITLE
Telegram Network Error was thrown

### ISSUE THREAD

**Issue by cofibit** [gcarq/freqtrade#627]
## Step 1: Have you search for this issue before posting it?

N/A

## Step 2: Describe your environment

  * Python Version: Python 3.6.4
  * Branch: Develop
  * Last Commit ID: 954c6e8c15095e9935dafd7f3055414687136b01
 
## Step 3: Describe the problem:
Bot is running but telegram Network Error was thrown hence bot doesn't respond to any commands on Telegram 

### Steps to reproduce:

 Just run freqtrade with Telegram enabled.
  
### Observed Results:

The following error was thrown:
2018-04-29 09:27:47,901 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Timed out! Trying one more time.
2018-04-29 09:27:53,847 - freqtrade.rpc.telegram - WARNING - TelegramError: Timed out! Giving up on that message

### Relevant code exceptions or logs:

  ```
2018-04-29 09:27:47,901 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Timed out! Trying one more time.
2018-04-29 09:27:53,847 - freqtrade.rpc.telegram - WARNING - TelegramError: Timed out! Giving up on that message
  ```

**Comment by xmatthias** [comment]
Does the bot actually crash or is it "just" throwing errors and not updating you?

in the latter - there is currently nothing to do as Telegram experienced an outage - the bot may do many things - but not fix outages of Telegram ...

**Comment by cofibit** [comment]
Bot runs okay it opens and closes the trade. But no interaction with Telegram. It doesn't respond to commands.

**Comment by xmatthias** [comment]
Not much to do if Telegram has a problem ... 
> Massive overheating in one of the Telegram server clusters may cause some connection issues for European users within the next couple of hours. Apologies for the inconvenience – the problem is being solved.

[source](https://twitter.com/telegram/status/990474364108894209)

**Comment by cofibit** [comment]
Closing this one Telegram is thr culprit.
