### ISSUE TITLE
Bidding with negative ask_last_balance value

### ISSUE THREAD

**Issue by demestav** [gcarq/freqtrade#632]
Often when trading in low volume pairs, it happens that the order is not fulfilled, and remains open. Even though setting `ask_last_balance` to 0 should ensure that the order is fulfilled since the bidding price **is** the asking price, it is possible to miss the opportunity and the order remains open.

I believe there are two options to mitigate this:
- Have the option to buy at market price which is bit risky but ensures order fulfillment
- Allow negative value for `ask_last_balance` i.e. bid at a higher price than asking price. Even though this will not ensure a fulfillment of the order, it should reduce the chance of getting one (with respect to `ask_last_balance: 0.0`)

**Comment by xmatthias** [comment]
for option 1 i think there was (or is) a plan to support market-orders (optional) with ccxt.

Once ccxt is ready, adding this should be farily straightforward. Not sure if anyone would want to invest time in the bittrex API to add this functionality now.

option 2 should be easy to add (or at least test with) [constants.py#L44](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/constants.py#L44) - changing `'minimum': 0,` to `'minimum': -1` (use at your own risk).

**Comment by demestav** [comment]
Thanks for the comments.

Yes I agree that ccxt is the way to go; it makes sense! Actually, I am using the ccxt branch as is with Kraken and works just fine.

With respect to option 2, if understand correctly, the line you refer to changes the allowed limits for the parameter. Does that mean that it will function as bidding on a higher price?

**Comment by demestav** [comment]
Great thanks. Closing this.
