### ISSUE TITLE
Missed Sell Order

### ISSUE THREAD

**Issue by LubLub** [gcarq/freqtrade#66]
Hi Guys, I recently noticed this issue when the bot made this trade.

Trade ID: 2
Current Pair: BTC_IOP
Open Since: 10 hours ago
Amount: 12.49968751
Open Rate: 0.00080002
Close Rate: 0.00080037
Current Rate: 0.00072
Close Profit: 0.04%
Current Profit: -10.00%
Open Order: 9.89177032 (LIMIT_SELL)

Since the market moved too quickly the bot's sell order for the BTC_IOP pair missed. 
After that, the sell order just stuck around until I manually canceled it from bittrex.
Perhaps a /cancel_order command from the telegram input could work to partially solve this issue?

**Comment by vertti** [comment]
True. We also make the limit sell orders with the "good until cancelled", I think we should either have the bot cancel them after certain time, or we should set the with a time limit on Bittrex when we create the order.

**Comment by LubLub** [comment]
I noticed that its the same case for buy orders.

Trade ID: 1
Current Pair: BTC_SNT
Open Since: 17 minutes ago
Amount: 1992.03187251
Open Rate: 5.02e-06
Close Rate: None
Current Rate: 5.17e-06
Close Profit: None
Current Profit: 2.99%
Open Order: 1790.82462904 (LIMIT_BUY)

**Comment by shusso** [comment]
Closing per #229
