### ISSUE TITLE
FIAT-Convert not working correctly, USD/EUR prices show as 0.

### ISSUE THREAD

**Issue by xmatthias** [gcarq/freqtrade#661]
* Branch: Develop
 
## Describe the problem:
* running `/profit` returns an empty fiat currency.
* all USD/EUR conversations return 0 or the BTC value

### Steps to reproduce:
* run the bot (dry or wet) and have it comlete at least one trade
* observe telegram

### Observed Results:
```
binance: Selling
Current Pair: ETH/BTC
Limit: 0.081371
Amount: 0.24669734
Open Rate: 0.08107100
Current Rate: 0.08137100
Profit: 0.17% (profit: 0.17%, 0.00003393 BTC / 0.000 USD)
```
### Expected results:
```
binance: Selling
Current Pair: ETH/BTC
Limit: 0.081371
Amount: 0.24669734
Open Rate: 0.08107100
Current Rate: 0.08137100
Profit: 0.17% (profit: 0.17%, 0.00003393 BTC / 0.290 USD)
```

I already had a look at it, looks to be an issue with a change in the coinmarketcap API (which changed from v1 to v2).

I'll submit a PR this evening - this is mainly opened as reference for others encountering the same issue.

**Comment by shusso** [comment]
should be fixed with #665

**Comment by rnaveen99-github** [comment]
Hi xmatthias

I have exactly same  issue when I run my bot. Please can you let me know how you solved this issue. Thank you.

**Comment by hroff-1902** [comment]
@rnaveen99-github 
please open a new issue for your problem, this one is old and is not relevant to the current codebase.
