### ISSUE TITLE
Gdax Precision Error On Buy

### ISSUE THREAD

**Issue by mshirley** [gcarq/freqtrade#676]
I'm receiving the following error when a buy order is sent to Gdax.

```2018-05-14 16:40:27,384 - freqtrade.freqtradebot - WARNING - Could not place buy order due to ExchangeError. Message: gdax size is too accurate. Smallest unit is 0.00000001, retrying in 30 seconds...```

I have added a debug statement to print out the rate the next time an order is made and I will update this error report when that happens.

I would expect that the rate precision is defined and controlled by ccxt so this issue may be in that library.  I'm going to manually create a ccxt instance and try a gdax buy using 8 digit precision which should be the default.

**Comment by mshirley** [comment]
Update.  I added a debug statement to show data being passed and the amount is 

```2018-05-14 20:18:56,669 - freqtrade.freqtradebot - WARNING - Could not place buy order due to ExchangeError. Message: gdax size is too accurate. Smallest unit is 0.00000001 Data: ['LTC/BTC', 1.7793594306049823, 0.01686], retrying in 30 seconds...```

Data:
```pair == 'LTC/BTC'
amount == 1.7793594306049823, 
rate == 0.01686```

Amount is 16 digits long and the longest accepted is 8 digits.

Should this value be rounded by freqtrade or by ccxt?

**Comment by shusso** [comment]
Hi @mshirley thanks for the issue 👍 For now, we only support Bittrex and Binance with `ccxt`. When we know that those work we'll start supporting more exchanges.

[Relevant](https://github.com/ccxt/ccxt/issues/1964) issue in ccxt.
