### ISSUE TITLE
Use Bittrex v2.0 API

### ISSUE THREAD

**Issue by xsmile** [gcarq/freqtrade#69]
Version [0.2.0](https://github.com/ericsomdahl/python-bittrex/releases) was released recently and supports the get_candles method accessing the API endpoint `/pub/market/GetTicks`.
freqtrade currently uses a custom method accessing the same endpoint to gather history data for analysis. It can be simplified after the update.

Additionally a default but adjustable sleep time of 1 second is introduced between all API calls. It might be better to disable it and rely on freqtrade to handle sleeping for a better compatibility to other possible exchanges.

**Comment by gcarq** [comment]
Good catch, I'll update it

**Comment by gcarq** [comment]
I created a branch which uses python-bittrex 0.2.0 and all v2.0 endpoints, but there are some changes I had to make, because v2.0 does no longer support `get_ticker` which returned bid, ask and last.
So the `get_target_bid` function does not interpolating between bid - ask instead of ask - last.
What are your opinions on this @vertti @xsmile 
https://github.com/gcarq/freqtrade/tree/feature/update-python-bittrex

**Comment by xsmile** [comment]
@gcarq Thanks for updating it this quickly.

- config.json.example: rename `ask_last_balance` to `bid_ask_balance`
- exchange.bittrex.get_orderbook: could remain as `get_ticker` returning `data['result']['{buy,ask}'][0]` to make it easier handling the return value in other parts of the application. The rest of the order book data isn't needed anywhere else, I think

Looks good otherwise.

**Comment by vertti** [comment]
Yeah, switching to balancing between ask and bid rather than ask and last is fine with me. It might actually be more predictable that way.

Ps. I think you should just right away make a PR out of these things, I hadn't noticed these comments at all.

**Comment by gcarq** [comment]
I will create a PR once it's ready, I just wanted your thoughts about switching to v2.0 and changing the `get_target_bid` logic

**Comment by shusso** [comment]
closing this as we are moving to ccxt
