### ISSUE TITLE
[ccxt] sqlalchemy.exc.IntegrityError thrown when buying on Bittrex

### ISSUE THREAD

**Issue by cofibit** [gcarq/freqtrade#743]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/gcarq/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: Python 3.6.4 :: Anaconda, Inc. (`python -V`)
  * Branch: Develop
  * Last Commit ID: 13d6297b9f52691b0bda1f867222b1c638e0c503 (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:

Bot crashed trying to buy WAX/BTC checking the log an Integrity error was thrown.

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * sqlite3.IntegrityError was thrown resulting to crash the bot.

### Relevant code exceptions or logs:

  ```
2018-05-22 15:48:04,959 - freqtrade.rpc.rpc_manager - INFO - *Bittrex:* Buying [WAX/BTC](https://bittrex.com/Market/Index?MarketName=BTC-WAX) with limit `0.00002800 (0.003000 BTC, 1294.921 PHP)` 
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: trades.stop_loss [SQL: 'INSERT INTO trades (exchange, pair, is_open, fee_open, fee_close, open_rate, open_rate_requested, close_rate, close_rate_requested, close_profit, stake_amount, amount, open_date, close_date, open_order_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('bittrex', 'WAX/BTC', 1, 0.0025, 0.0025, 2.8e-05, 2.8e-05, None, None, None, 0.003, 107.14285714285715, '2018-05-22 15:48:06.125126', None, 'b90f4fc6-332d-40b5-b045-b6b6ad29441d')] (Background on this error at: http://sqlalche.me/e/gkpj)
  ```

**Comment by xmatthias** [comment]
the code might be develop *now* - but the database was definitely used in a stop-loss branch - which added a `not-null` column to the database.

You could either open the database with sqlite3 or sqlitebrowser and drop the column `stop_loss` (which might be recreated once you use the stop-loss branch again) - or start with a fresh database to fix this problem.

Unfortunately this is nothing which can (should?) be fixed in the develop-code.

**Comment by cofibit** [comment]
Closing this one was using a different branch.
