### ISSUE TITLE
"/buy amount" support

### ISSUE THREAD

**Issue by yaotian** [gcarq/freqtrade#758]
It's lovely if "/buy symbol amount" support on telegram.

It means that user can *manually* buy a currency pair by telegram.

**Comment by iliecosmin** [comment]
or "/forcebuy <symbol>" on Telegram. Bot to check if not max number of trades and if sufficient funds then trigger a buy. I think it's the only thing missing to be perfect.

**Comment by vertti** [comment]
We have discussed this before. It would be highly unpredictable to buy manually as the bot could for example immediately sell the same coin. The bot is focused on being a frequency trader and we do not want to add manual trading features to it.

**Comment by iliecosmin** [comment]
Hi,

Understand. Tks!
Can you tell me why is doing this?

CHOOD trading bot:
cobinhood: Selling
Current Pair: TRX/ETH
Limit: 7.93e-05
Amount: 408.580184
Open Rate: 0.00009790
Current Rate: 0.00007930
Profit: -19.00% (loss: -19.00%, -0.00759959 ETH / -4.655 USD)

COBINHOOD: Buying TRX/ETH with limit 0.00009780 (0.040000 ETH, 24.501 USD)

cobinhood: Selling
Current Pair: TRX/ETH
Limit: 7.93e-05
Amount: 408.997955
Open Rate: 0.00009770
Current Rate: 0.00007930
Profit: -18.83% (loss: -18.83%, -0.00752556 ETH / -4.610 USD)

COBINHOOD: Buying TRX/ETH with limit 0.00009780 (0.040000 ETH, 24.501 USD)

cobinhood: Selling
Current Pair: TRX/ETH
Limit: 7.93e-05
Amount: 408.997955
Open Rate: 0.00009770
Current Rate: 0.00007930
Profit: -18.83% (loss: -18.83%, -0.00752556 ETH / -4.610 USD)

It is like is using sell and bid price to place orders. Can it be configured to use like medium or market this way to prevent this?

Cheers,
Cosmin
Thank you!



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: Janne Sinivirta <notifications@github.com>
Fecha: 2/6/18 10:46 (GMT+01:00)
Para: gcarq/freqtrade <freqtrade@noreply.github.com>
Cc: iliecosmin <iliecosmin@hotmail.com>, Comment <comment@noreply.github.com>
Asunto: Re: [gcarq/freqtrade] "/buy amount" support (#758)


We have discussed this before. It would be highly unpredictable to buy manually as the bot could for example immediately sell the same coin. The bot is focused on being a frequency trader and we do not want to add manual trading features to it.
