### ISSUE TITLE
Gdax Buy Warning Message

### ISSUE THREAD

**Issue by carpionetwork** [gcarq/freqtrade#759]
## Step 1: Have you search for this issue before posting it? Yes

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/gcarq/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _3.6__ 
  * Branch: Develop
  * Last Commit ID: __4e0b095f2bd32cd3f8671e47333eabddf2902548___ 
 
## Step 3: Describe the problem:
- "stake_amount": 0.01
- exchange: gdax
- pairs: ltc/btc & eth/btc

Bot starts up correctly.
While processing 'Checking buy signals to create a new trade … stake_amount: 0.010000 …
WARNING - Could not place buy order due to ExchangeError.  Message: gdax size is too accurate.  Smallest unit is 0.00000001, retrying...

I have run /setup.sh -u and ./setup.sh -r and after bot startup both returned the same warning message.  I have also tried setting a diff stake_amount.

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by mshirley** [comment]
same issue?

https://github.com/gcarq/freqtrade/issues/676

Gdax isn't officially supported yet.  I'm also waiting for that support, but in the meantime I've moved over to bittrex and bot is working well.

**Comment by shusso** [comment]
Thanks for the issue 👍 At the moment, we only support Bittrex and Binance.
