### ISSUE TITLE
MACD buy signal

### ISSUE THREAD

**Issue by vertti** [gcarq/freqtrade#8]
Opening this for discussion:

Currently we use buy signal condition `MACD > MACDS`. According to for example this: http://www.onlinetradingconcepts.com/TechnicalAnalysis/MACD2.html the buy signal is when the crossover happens from `MACD < MACDS` to `MACD > MACDS`.

How about changing it to something like "if currently MACD > MACDS and the previous sample (one minute earlier) is MACD < MACDS" to give the buy signal? The current rule gives the signal all the way to the point when the sell already should happen.

**Comment by vertti** [comment]
Actually same seems to apply for StochRSI: http://www.onlinetradingconcepts.com/TechnicalAnalysis/StochasticRSI.html

So we should apply similar technique to that: instead of watching only if it's below 20, we should spot the moment it goes from below 20 to above 20.

**Comment by vertti** [comment]
<img width="582" alt="screenshot 2017-09-03 11 25 08" src="https://user-images.githubusercontent.com/557751/30001572-a3400fbc-909a-11e7-8c76-9d0f9acdf0d6.png">

Well, it seems that at the fluctuation speed of the fast stochastic rsi, using just the crossover point would make us almost always late in buying.

The above graph has buy points only when we crossover from <20 to >20. Here's the buy points with the rule of "always buy when <20":

<img width="579" alt="screenshot 2017-09-03 11 28 31" src="https://user-images.githubusercontent.com/557751/30001597-37d9ffca-909b-11e7-9d8f-e6043f17216b.png">

**Comment by vertti** [comment]
Then again, maybe it's not realistic to try catch the jumps in the one-minute ticker. Either using slower stoch oscillator or slower ticker might be worth testing too.

**Comment by vertti** [comment]
To be honest, I'm having hard time to get MACD or StochRSI to give me good buy signal, either with the current strategy or the one I proposed above. The one-min ticker is ridiculously volatile to make any predictions with.

**Comment by gcarq** [comment]
Yes, I feel with you.. In addition to that the delivered price charts from BITTREX are sometimes slightly out of date for one or two minutes. Did you have some luck with parabolic SAR?

**Comment by vertti** [comment]
Parabolic SAR seems to be the only definite winner, it saves you from trading on clearly down trending currencies. But I would use it with one or two other indicators.

We now have 150 indicators that TA-lib supports, so I guess we just have to combine our efforts in searching for other good indicators. I know few bots use just EMA based algorithms, I know one bot that uses PPO instead MACD, and I know that TA-lib supports also pattern recognitions which might be voodoo or something really interesting :).

As a side note, I think the fact that our bot new buys on current ask price is too high. We should maybe look in to using something between 'last' and 'ask' to combine fast buys with slightly better prices?
