### ISSUE TITLE
Graceful handling of shutdown (SIGKILL)

### ISSUE THREAD

**Issue by shusso** [gcarq/freqtrade#81]
We should handle `Control-C` much more nicely what it currently is

**Comment by gcarq** [comment]
I think you are refering to SIGINT, which is sent by `Control-C`. SIGKILL cannot be caught

**Comment by shusso** [comment]
Oh true, my bad. I'll update the issue 👍

**Comment by gcarq** [comment]
I created a PR to fix this: #82
