### ISSUE TITLE
Autoselect top 50 currencies

### ISSUE THREAD

**Issue by bodaum** [gcarq/freqtrade#98]
How to call the top50 pairs with function ?

**Comment by gcarq** [comment]
I guesss you are referring to `--dynamic-whitelist`.
Right now it's not configurable via paramters, but there are plans for it. Any PR is welcome

**Comment by glonlas** [comment]
@bodaum, I made a PR for this request: https://github.com/gcarq/freqtrade/pull/173

**Comment by glonlas** [comment]
@bodaum the PR is merged, you can now select how many Pairs you want to retrieve.

If no other question we can close this issue

**Comment by gcarq** [comment]
@glonlas Thanks a lot for implementing this. I'm closing it. Feel free to reopen if there are any questions
